- .gitignore
- pom.xml
Findbugs was declared twice with different configurations so removed the one that checked for the least amount of issues.
Add eclipse findbugs config file to .gitignore
@reviewbybees
> Fix bad pom and ignore eclipse file

- src/test/java/hudson/remoting/PrefetchingTest.java
do not compare a URI path with a File Path - it is doomed to fail on Windows.
The unit tests in question still have some issues on windows as they fail to clean up resources that are locked - however at least you see the asserts passing.
@reviewbybees
> Fix unit test issue on windows.

- src/main/java/hudson/remoting/AtmostOneThreadExecutor.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/PingThread.java
- src/main/java/hudson/remoting/Request.java
- src/main/java/hudson/remoting/SingleLaneExecutorService.java
- src/main/java/hudson/remoting/SynchronousExecutorService.java
Initial calculation of wait time was susceptible to clock drift.
The calculation on how long to wait in various places on the code was
susceptible to the clock changing as multiple calls where made to
System.currentTimeMillis() for the initial calculation.
Changed this so that we use a single call to System.nanoTime and made just
a single call for the initial calculation.
There is still a potential issue for any callers of Channel.getLastHeard()
this will be addressed in a future change and has only been noted in this
commit.
Replaces Pull #29 which was getting multiple different fixes intertwined.
@reviewbybees
> [JENKINS-21251] Slave channel timeout seemingly caused by usage of System.currentTimeMillis()

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/Util.java
We get proxy setting from http_proxy environment variable.
https://issues.jenkins-ci.org/browse/JENKINS-6167
> [JENKINS-6167] Support JNLP slave connection via HTTP proxy

- src/main/java/hudson/remoting/Checksum.java
- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/JarLoaderImpl.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/test/java/hudson/remoting/ChecksumTest.java
- src/test/java/hudson/remoting/FileSystemJarCacheTest.java
[JENKINS-26759](https://issues.jenkins-ci.org/browse/JENKINS-26759)
After a jar is fetched verify the checksum matches the expected value, if not throw an exception.
> [JENKINS-26759] Make FileSystemJarCache more defensive

- pom.xml
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/JarCacheSupport.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/NamingThreadFactory.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/test/java/hudson/remoting/ChannelTest.java
- src/test/java/hudson/remoting/util/GCTask.java
See [JENKINS-28844](https://issues.jenkins-ci.org/browse/JENKINS-28844) 
* In larger installations of Jenkins the complex cycles of object references containing classloaders containing references to the channel which contains references back to the classloaders can confuse the garbage collector.
* The confusion arrises because classloaders are considered live while there are objects from the classloader live
and the RemoteClassLoader and RemoteInvocationHandler's proxy both need a reference to the Channel
which typically can be storing either some of the objects from the RemoteClassLoader or
the RemoteInvocationHandler's proxy instances in the Channel properties. Thus although the entire subgraph
is no longer live, the cycle is not detected as ClassLoaders are treated separately. The …
> [JENKINS-28844] Fix memory leak

- src/main/java/org/jenkinsci/remoting/RoleChecker.java
- src/main/java/org/jenkinsci/remoting/RoleSensitive.java
After about the seventeenth Jenkins plugin pull request (most recently https://github.com/jenkinsci/analysis-core-plugin/pull/31) featuring something like
```java
@Override
public void checkRoles(RoleChecker checker) throws SecurityException {
// TODO what do we need to do here?
}
```
I am trying to guide people to the answer, in case they read Javadoc anyway.
(For SECURITY-144 we explicitly decided to introduce `RoleSensitive` despite the source incompatibility, while keeping a binary-compatible runtime behavior, since every plugin author really must decide how a given callable is _intended_ to be used.)
@reviewbybees
> Trying to guide people away from implementing RoleSensitive manually

- src/test/java/org/jenkinsci/remoting/engine/JnlpProtocol2Test.java
PowerMockito wasn't being told to prep Properties.class to have its
'new Date()' call hijacked, so it wasn't actually doing it. That said,
even adding that didn't seem to help.
But instead of reaching into the implementation details, I've written a
custom Matcher to just verify that the output string representation of
the Properties parses back to the expected values. As an added benefit,
this no longer depends on two identical Properties objects writing keys
in the same order when store() is called, since the API there doesn't
actually guarantee that.
> Deflake JnlpProtocol2Test

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/Checksum.java
- src/main/java/hudson/remoting/JarLoaderImpl.java
- src/test/java/hudson/remoting/ChecksumTest.java
Only calculate checksums for Jars once. This change reduces the stress on the Jenkins master when several slaves connect to it simultaneously, allowing Jenkins to scale more gracefully when dealing with a high number of ephemeral slaves that comes & go. This is particularly helpful when there are large Jars involved, as the case may be in some custom plugins or if the user puts custom jars in the Jenkins classpath.
> [JENKINS-28127] Checksum caching to improve performance when dealing with high number of slaves

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Util.java
Pull request as planned : https://issues.jenkins-ci.org/browse/JENKINS-28289
> [JENKINS-28289] Ensure proxy exclusion list is used while getting proxy for JNLP clients

- src/main/java/hudson/remoting/InitializeJarCacheMain.java
Add a utility main that can populate a jar cache dir given another directory of jars.
This can be used to initialze a node's jar cache ahead of time before it connects to the master. This has performance benefits for the master as it won't have to transfer jars over to the node.
> Add a utility main that can be used to initialize a node's jar cache

- src/main/java/hudson/remoting/PipeWindow.java
- src/main/java/org/jenkinsci/remoting/nio/FifoBuffer.java
The error happens when starting approximately 100 build jobs with "once only" build executors as used with the mesos plugin. In our scenario we have approximately 20 active build executors, that are disconnected at approximately the same time. During termination of the channels we get the thread starvation described below.
In Example below Lock 0x27a7 was acquired by the thread pool (on the channel), but required by RemoteInvocationHandler and NioChannelHub. The Fifo Buffer / Pipe Window never released the lock in the wait. So i introduced a timeout and this seems to do the trick.
"Computer.threadPoolForRemoting [#1748] for build4G-6G-mesos-70dd9b11-d5f4-43eb-b914-7604285a6e7c@9817" daemon prio=5 tid=0x56ff nid=NA waiting
  java.lang.Thread.State: WAITING
blocks RemoteInvocationHandler …
> Thread starvation on close / terminate slaves channel.

- src/test/java/hudson/remoting/AbstractNioChannelRunner.java
I have found that while tests reliably pass for me on Java 7, when using Java 8 I often get some failures about the “south” channel not being closed. Not sure why, exactly, but I suspect a race condition—`CloseCommand` not having been processed by the time the assertion is run?
@reviewbybees esp. @kohsuke, @oleg-nenashev
> Test failures on Java 8

- src/main/java/org/jenkinsci/remoting/nio/FifoBuffer.java
See [JENKINS-32925](https://issues.jenkins-ci.org/browse/JENKINS-32825)
Additional `closed` state check introduced to break writing loop.
@reviewbybees
> [JENKINS-32825] Deadlock in Channel Abort

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/jnlp/Main.java
PEM encoded certificates to trust when performing JNLP port discovery on the supplied Jenkins URLs
@jenkinsci/code-reviewers @reviewbybees
> [FIXED JENKINS-32980] Adds a new CLI option to specify additional X.509 certs

- src/main/java/hudson/remoting/SocketInputStream.java
- src/main/java/hudson/remoting/SocketOutputStream.java
@reviewbybees
Spotted this one while doing some testing. Getting exceptions like
```
Mar 03, 2016 5:22:19 PM hudson.remoting.Channel terminate
WARNING: Failed to close down the reader side of the transport
java.net.SocketException: Socket is closed
at java.net.Socket.shutdownInput(Socket.java:1514)
at hudson.remoting.SocketInputStream.close(SocketInputStream.java:56)
at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
at hudson.remoting.FlightRecorderInputStream.close(FlightRecorderInputStream.java:112)
at hudson.remoting.ChunkedInputStream.close(ChunkedInputStream.java:113)
at hudson.remoting.ChunkedCommandTransport.closeRead(ChunkedCommandTransport.java:56)
at hudson.remoting.Channel.terminate(Channel.java:837)
at …
```
> Don't try to close a socket that is already closed

- src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
@reviewbybees
Caught this one while testing...
```
Mar 03, 2016 5:39:32 PM hudson.remoting.AbstractByteArrayCommandTransport$1 handle
WARNING: Failed to construct Command
java.io.EOFException
at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2328)
at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2797)
at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)
at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:594)
at …
```
> Dont try to handle empty packets

- src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol3.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpServer3Handshake.java
- src/test/java/org/jenkinsci/remoting/engine/JnlpProtocol3Test.java
Server who doesn't understand the JNLP3 protocol sends us a line like
"Unknown protocol:....", whereas the protocol expects an integer.
This results in the following exception:
SEVERE: For input string: "Unknown protocol:Protocol:JNLP3-connect"
java.lang.NumberFormatException: For input string: "Unknown protocol:Protocol:JNLP3-connect"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:492)
at java.lang.Integer.parseInt(Integer.java:527)
at org.jenkinsci.remoting.engine.JnlpProtocol3.initiateAndValidateMaster(JnlpProtocol3.java:185)
at org.jenkinsci.remoting.engine.JnlpProtocol3.performHandshake(JnlpProtocol3.java:141)
at org.jenkinsci.remoting.engine.JnlpProtocol.establishChannel(JnlpProtocol.java:77)
at …
> Need a line with known text to find failures

- src/main/java/hudson/remoting/ClassFilter.java
- src/test/java/hudson/remoting/DefaultClassFilterTest.java
`NestedRuntimeException` and others needs to be propagated across remoting for things
like remote authentication schemes.
@reviewbybees
[JENKINS-33999](https://issues.jenkins-ci.org/browse/JENKINS-33999)
> [JENKINS-33999] Do not blacklist Spring’s Exceptions

- src/main/java/hudson/remoting/Engine.java
we encounter slave offline issue when executing commands like 
`
sleep 40m
`
on jnlp agent, the socket read timeout is hard coded to 30 minutes and caused the issue
> Allow user to adjust socket timeout

- src/main/java/hudson/remoting/RemoteInvocationHandler.java
> [FIXED JENKINS-34213] Ensure that the unexporter cleans up whatever it can each sweep

- src/main/java/hudson/remoting/UserRequest.java
This is a workaround to force class load of any class. This helps prevent deadlock on windows nodes when using JNA and Subversion.
Use property hudson.remoting.RemoteClassLoader.force to name the class to load. Ideally this forced load should happen earlier on the startup, however the classloader isn't available.
link: https://issues.jenkins-ci.org/browse/JENKINS-19445
> Force class load on UserRequest, see JENKINS-19445

- src/main/java/hudson/remoting/Engine.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol.java
- Also ensure that a fatal unexpected error in one protocol does not prevent a fall-back
@reviewbybees
> [Related to JENKINS-34121] Allow disabling the protocols individually

- src/main/java/hudson/remoting/Util.java
- src/test/java/hudson/remoting/UtilTest.java
https://issues.jenkins-ci.org/browse/JENKINS-32326
> [FIXED JENKINS-32326] Support no_proxy environment variable

- src/main/java/hudson/remoting/SynchronousCommandTransport.java
This change prevents failures of the remoting channel on SocketTimeout exceptions if the channel is in the operational state after it. The original behavior can be restored by setting a system property.
It should be a more graceful fix of the issue, which @fengxx was trying to fix in https://github.com/jenkinsci/remoting/pull/68
@reviewbybees @KostyaSha @fengxx @jtnord
> [JENKINS-22722] - Make AsynchronousCommandTransport tolerant against Socket timeouts

- src/main/java/hudson/remoting/ClassFilter.java
If the first access of the ClassFilter is from a class being auto wired
then the root cause of the Issue can get swallowed and it is not clear in
the logs what is wrong.  So if something goes wrong always log the error
at the expense that it gets logged twice (which is not a bad thing as it
is fatal anyway and will cause Jenkins to pretty much not work at all)
@reviewbybees
> Ensure a message is logged if we can not create an override

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Util.java
It's a follow-up to #67 
> This patch addresses three regressions introduced with HUDSON-4071, 662b0f and JENKINS-6167 as these only modified run() resulting in no proxy and no authorization support in waitForServerToBack()
> As a result the connection to the master could not be reestablished as connections were rejected with response code 401 as reported in JENKINS-31256.
https://issues.jenkins-ci.org/browse/JENKINS-31256
CC @wiizzard @reviewbybees
> [JENKINS-31256] Use credentials in waitForServerToBack

- src/main/java/hudson/remoting/Launcher.java
> [JENKINS-35494] - FindBugs - fix minor File Management issues in hudson.remoting.Launcher

- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/test/java/hudson/remoting/ClassRemotingTest.java
… while fetching ClassRefference
Fixing [JENKINS-36991](https://issues.jenkins-ci.org/browse/JENKINS-36991), a variant of [JENKINS-19453](https://issues.jenkins-ci.org/browse/JENKINS-19453).
@jenkinsci/code-reviewers (esp. @jglick and @kohsuke)
> [FIXED JENKINS-36991] Do not give up on classloading if loading is interrupted

- pom.xml
- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/InitializeJarCacheMain.java
- src/main/java/hudson/remoting/Util.java
- src/test/java/hudson/remoting/FileSystemJarCacheTest.java
- src/test/java/hudson/remoting/UtilTest.java
https://issues.jenkins-ci.org/browse/JENKINS-36947
> Improve diagnostics for JarCache write errors (related to JENKINS-36947)

- src/main/java/hudson/remoting/Engine.java
See [JENKINS-37031](https://issues.jenkins-ci.org/browse/JENKINS-37031) and https://github.com/jenkinsci/jenkins/pull/2486
> [FIXED JENKINS-37031] tcpSlaveAgentListener should publish supported agent protocols to speed up connection setup

- pom.xml
- src/findbugs/excludeFilter.xml
- src/main/java/hudson/remoting/Base64.java
- src/main/java/hudson/remoting/CallableDecoratorAdapter.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelBuilder.java
- src/main/java/hudson/remoting/DumbClassLoaderBridge.java
- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/ExportTable.java
- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/Future.java
- src/main/java/hudson/remoting/InitializeJarCacheMain.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/ReferenceCountRecorder.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/hudson/remoting/Which.java
- src/main/java/hudson/remoting/jnlp/GuiListener.java
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/hudson/remoting/jnlp/MainDialog.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpServer3Handshake.java
I would like to restore FindBugs checks in the code. Current filters hide away much real issues, and I would rather admit issues and try to fix it instead of hiding my head in sand.
@reviewbybees
> FindBugs - Reconsider filters and cleanup some issues

- src/main/java/hudson/remoting/Util.java
It may happen in the case of the remote classloader.
https://scan8.coverity.com/reports.htm#v14462/p10499/fileInstanceId=12836386&defectInstanceId=4427346&mergedDefectId=48110
@jenkinsci/code-reviewers
> [CID-48110] - Resource leak on exceptional path in Util#makeResource()

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Util.java
Bug diagnosis:
* https://scan8.coverity.com/reports.htm#v14462/p10499/fileInstanceId=12836372&defectInstanceId=4427367&mergedDefectId=152195
* https://scan8.coverity.com/reports.htm#v14462/p10499/fileInstanceId=12836372&defectInstanceId=4427365&mergedDefectId=152194
https://issues.jenkins-ci.org/browse/JENKINS-37539
@reviewbybees
> [FIXED JENKINS-37539] - Prevent NPE in Engine#connect() when host or port are null or empty

- src/main/java/org/jenkinsci/remoting/engine/EngineUtil.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpServer3Handshake.java
* https://scan8.coverity.com/reports.htm#v14462/p10499/fileInstanceId=12836377&defectInstanceId=4427377&mergedDefectId=152202
* https://scan8.coverity.com/reports.htm#v14462/p10499/fileInstanceId=12836377&defectInstanceId=4427377&mergedDefectId=152200
> [CID-152200,CID-152202] - Resource leak in Cipher I/O streams on exceptional paths

- pom.xml
This change does not update the code to the Java7 style, but we will do it later. It requires https://github.com/jenkinsci/pom/pull/11
> [JENKINS-37565] - Upgrade source level to Java 7

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Util.java
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/org/jenkinsci/remoting/engine/EngineUtil.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Integrates pending changes from the stable branch
> Merge stable-2.x into master

- src/main/java/org/jenkinsci/remoting/protocol/impl/BIONetworkLayer.java
[JENKINS-38541](https://issues.jenkins-ci.org/browse/JENKINS-38541)
@reviewbybees @jenkinsci/code-reviewers @jtnord
> [FIXED JENKINS-38541] SocketTimeoutException should not be fatal for BIONetworkLayer

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/jnlp/Main.java
See [JENKINS-38539](https://issues.jenkins-ci.org/browse/JENKINS-38539)
Will need to be merged up to master also
> [FIXED JENKINS-38539] Turn on SO_KEEPALIVE and provide CLI option to turn it off again

- src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java
Replaces #115
@reviewbybees
All tests pass on my machine.
| "protocol"                         | "io"           | "clients" | "interval" | "payload" | "observedRate" | "expectedRate" | "vmLoad" | "expectedVmLoad" | "threads" | "avgMemory" | "stdMemory" | "dfMemory" | "maxMemory" | "gc[0].name"             | "gc[0].count" | "gc[0].time" | "gc[1].name"  | "gc[1].count" | "gc[1].time" | 
|------------------------------------|----------------|-----------|------------|-----------|----------------|----------------|----------|------------------|-----------|-------------|-------------|------------|-------------|--------------------------|---------------|--------------|---------------|---------------|--------------| 
| "JNLP4-plaintext (this change)"    | "non-blocking" | 100       | 100        | …
> [JENKINS-38690] Do not cause a Thread storm in IOHub

- src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java
[JENKINS-38690](https://issues.jenkins-ci.org/browse/JENKINS-38690)
We should only add the READ interested OPS when we have fully drained the
read queue.
In the case we had a lot of data to read (where lots >> 8192 bytes) we
would read a buffers worth of data add READ to the interested opps then
read another buffer in the same thread.  If we where reading 81920 bytes
for example this would be 9 calls to add READ OPs - which would run on the
selctor thread and cause an immediate wakeup to be called followed by a
new onReady().
However the onReady will be added as a defered callback and the ops
removed, but the read thread is still going and as it takes time will call
back again to add interested ops... which will wake the selector see that
READ ops are valid and cause a new deffered …
> [JENKINS-38690] do not cause a IOHub Thread Storm

- src/main/java/hudson/remoting/Request.java
I was trying to diagnose a remoting call that bridges two VMs that is hanging. This can be made easier if thread dump allows us to correlate the caller/callee.
This change adds the request ID to thread name so that thread dump will show this clearly
Also fixes one incorrect use of `toString()` in diagnosis, which should be `getName()` --- see all the other uses of thread names.
@reviewbybees
> Improve the caller/callee correlation diagnostics

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/Command.java
- src/test/java/hudson/remoting/ChannelTest.java
Continuing from https://github.com/jenkinsci/remoting/pull/120
No code change since then, just re-targeting stable-2.x
> [JENKINS-39150] expose diagnostics across all the channels

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/configuration.md
- docs/jenkins-specifics.md
- docs/protocols.md
- docs/remoting-3-compatibility.md
- docs/troubleshooting.md
Plan:
- POSTPONED:  -NEW: Jenkins Specifics page with configuration guidelines: configuring protocols, restricting versions, using in Docker, etc.-
@reviewbybees @jenkinsci/code-reviewers 
https://issues.jenkins-ci.org/browse/JENKINS-39161
> [JENKINS-39161] - Remoting documentation upgrade for the 3.0 release

- CHANGELOG-2.x.md
For a better maintenability, I want to keep Remoting 2.x is a separate changelog.
Once the PR is merged to stable and the branch gets integrated to master, I'll also put links to README and the main changelog
> Decouple remoting-2.x changelog to a separate file

- Jenkinsfile
The maven command should use batch mode - otherwise the logs are an unintelligible mess containing output of the amount of KB downloaded when downloading dependencies.
@oleg-nenashev @rtyler
> Maven command should use `--batch-mode`

- pom.xml
- src/main/java/hudson/remoting/Channel.java
In https://github.com/jenkinsci/remoting/pull/122 @kohsuke merged the pull request without waiting for the feedback from reviewers. It effectively introduced new public API in the stabilization branch.
I also used my chance to review the code deeply and realised that <code>IOException</code> handling is far from ideal for the production code. Hence I propose to change it as well
@reviewbybees
> [JENKINS-39150] - API stabilization && compliance with the compatibility policy

- src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java
[JENKINS-38692](https://issues.jenkins-ci.org/browse/JENKINS-38692) Add extra logging statements to try and get to the root cause
of the IOHub thread spike.
@reviewbybees esp @stephenc
> [JENKINS-38692] Add extra logging to help diagnosing Thread spike.

- docs/configuration.md
- pom.xml
- src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
To further isolate problems during remote trouble-shooting of remoting, define a switch to bypass NIO and use classic blocking I/O transport.
Ample warning to prevent accidental dependencies from other Java code.
> [FIXED JENKINS-39290] A debug flag to disable NIO

- src/main/java/hudson/remoting/Engine.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Starting from Jenkins 2.16 (remoting 3.0) JNLP agents cannot be connected via Java Web Start [JENKINS-39596](https://issues.jenkins-ci.org/browse/JENKINS-39596). It happens, because Slave Installer Module in Jenkins core relies on the `hudsonUrl` in `hudson.remoting.Engine`, but starting from remoting 3.0 this field was alway null. Hence we were getting crappy exceptions in Jenkins, which were blocking the agent connection:
```
java.net.MalformedURLException: no protocol: jnlpJars/slave.jar
at java.net.URL.<init>(URL.java:593)
at java.net.URL.<init>(URL.java:490)
at org.jenkinsci.modules.slave_installer.impl.InstallerGui.call(InstallerGui.java:65)
at org.jenkinsci.modules.slave_installer.impl.InstallerGui.call(InstallerGui.java:34)
at …
```
> [JENKINS-39596,JENKINS-39617] - hudsonUrl in Remoting Engine was always null since 3.0

- src/main/java/org/jenkinsci/remoting/nio/FifoBuffer.java
The most of [JENKINS-25218](https://issues.jenkins-ci.org/browse/JENKINS-25218) has been handled in https://github.com/jenkinsci/remoting/commit/3ea38c8b95a8d4ca8e245fc0999d7e4a9a6b1424 by @andresrc. But there are still potential issues in the FifoBuffer behavior.
Changes:
@reviewbybees
> [JENKINS-25218] - Hardening of FifoBuffer operation logic

- docs/protocols.md
Seems like "like for like" might exist, but IMO it makes the sentence a bit more complicated that required.
And as a non-native person, it felt surprising, so maybe without it it'll be a bit easier to read.
@reviewbybees
> Docs - Rephrasing JNLP4-plaintext a bit to clarify

- src/main/java/hudson/remoting/ProxyException.java
Potentially relevant for Pipeline, especially after https://github.com/jenkinsci/workflow-api-plugin/pull/18.
@reviewbybees
> ProxyException should also retain any suppressed exceptions from the original

- src/main/java/hudson/remoting/Checksum.java
- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/JarLoaderImpl.java
- src/test/java/hudson/remoting/ChecksumTest.java
- src/test/java/hudson/remoting/FileSystemJarCacheTest.java
[JENKINS-39547](https://issues.jenkins-ci.org/browse/JENKINS-39547)
- Verify checksum after loaded from slave jar cache on agent side.
- Extract checksum caching from `Checksum` class to `JarLoaderImpl` and `FileSystemJarCache`.
- It was done twice on master side and made the system more fragile on both ends.
- I wonder if we need checksum cashing on agent side at all as we should rarely call `#retrieve` on same jar more than once between agent restarts. Getting rid of it would improve this fix as it would detect jar cache manipulation without restart.
> [JENKINS-39547] - Corrupt jar cache

- src/main/java/org/jenkinsci/remoting/nio/FifoBuffer.java
- src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
When NioChannelHub suffers from the preliminary buffer closure, it will print a SEVERE log to the Agent log. This change should improve diagnostics of issues like [JENKINS-31050](https://issues.jenkins-ci.org/browse/JENKINS-31050), which has been likely somehow addressed/fixed in #100.
https://issues.jenkins-ci.org/browse/JENKINS-40491
@reviewbybees
> [JENKINS-40491] - Improve diagnostincs of the preliminary FifoBuffer termination

- src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java
[JENKINS-39835](https://issues.jenkins-ci.org/browse/JENKINS-39835) Be even more defensive then against leaving connections dangling.
NB: no testing performed of this fix - it is a direct port from the internal code that was submitted to make the JNLP v4 protocol.
@reviewbybees esp @stephenc @oleg-nenashev
> [JENKINS-39835] - Be extra defensive about Errors and Exceptions

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Untested (tests seem broken for me).
[JENKINS-40710](https://issues.jenkins-ci.org/browse/JENKINS-40710)
> [FIX JENKINS-40710] Match headers case-insensitively

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
I just tested this fix (I filed the bug) and ran into an NPE (even when there are headers, it appears the keyset contains null), and then realized it was still returning null even after matching because it was indexing into the map with the incorrectly cased header.
* https://issues.jenkins-ci.org/browse/JENKINS-41513
* https://issues.jenkins-ci.org/browse/JENKINS-40710
> [FIX JENKINS-40710, JENKINS-41513] Add null check, use correct header for map key

- pom.xml
Hoping this will deal with errors like in #141.
Was unable to run a build on Windows, since it fails inside VirtualBox when trying to get the owner of a file during `assembly`. Probably a VBox shared filesystem bug.
@reviewbybees
> Try to handle flaky tests

- src/main/java/hudson/remoting/MultiClassLoaderSerializer.java
> Fix useless exception message

- src/main/java/hudson/remoting/ExportTable.java
See [JENKINS-41852](https://issues.jenkins-ci.org/browse/JENKINS-41852)
@reviewbybees
> [FIXED JENKINS-41852] Tweak pinning logic

- src/main/java/hudson/remoting/Capability.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/Command.java
- src/main/java/hudson/remoting/MimicException.java
- src/main/java/hudson/remoting/ProxyException.java
`ProxyException` dates back to 2007 in 2515c1cddf732d5af6120060a2055b6795addf92. Yet for some reason @kohsuke added the nearly identical `MimicException` in 2012 in d084f5095f11a8bcb80913266d664b9d1f17dc3b. There is no reason to have both, especially when #136 improved the former.
The capability is unnecessary since `ProxyException` predates the introduction of capabilities themselves, in b310dd5443799a755b19631b88cef5c5a985dc2d in 2009.
Possibly `MimicException` could be simply deleted, not just deprecated, though it is not obvious to me whether it might be serialized somewhere on disk.
@reviewbybees esp. @oleg-nenashev
> Replacing MimicException with the older ProxyException

- docs/configuration.md
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
In particular cases the `X-Jenkins-Agent-Protocols` response header may change (e.g. due to the improperly configured proxy). This change adds diagnostics for such case and also adds a system property, which allows working around the issue by sacrificing the performance.
https://issues.jenkins-ci.org/browse/JENKINS-41730
@reviewbybees, esp. @stephenc
> [JENKINS-41730] - Add option to ignore the X-Jenkins-Agent-Protocols header

- docs/configuration.md
- src/main/java/hudson/remoting/Base64.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ErrorPropagatingOutputStream.java
- src/main/java/hudson/remoting/ExportTable.java
- src/main/java/hudson/remoting/LocalChannel.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/hudson/remoting/VirtualChannel.java
During last releases we have fixed several issues related to the object export/unexport operations (JENKINS-23271, JENKINS-41852). I decided that it makes sense to improve the method documentation just to make Javadocs more explicit.
The change also adds missing documentation of `hudson.remoting.ExportTable.unexportLogSize`
@reviewbybees
> Document and annotate object Export/Unexport logic

- docs/protocols.md
Improve docs: link to Oracle JDK8 security encryption algorithms and ciphers for the SSLEngine
> Improve docs: link to Oracle JDK8 security encryption algorithms and ciphers for the SSLEngine

- src/main/java/hudson/remoting/Launcher.java
Release the network resource(s) held by the underlying connection(s?):
- during retry attempts
- after obtaining the JNLP connection arguments
> [FIXED JENKINS-42371] - Call disconnect() on HttpURLConnection object

- docs/protocols.md
- src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol3Handler.java
Once the pull request is merged, the issues will be closed as "Won't fix".
JNLP4 protocol is enabled by default and battle-tested enough, so I doubt it makes sense to maintain JNLP3 anymore. The only concerns is the `stable-2.x` branch, but for that one the recommended solution is to use JNLP2 (with encryption tunnels if required).
* https://issues.jenkins-ci.org/browse/JENKINS-37302
* https://issues.jenkins-ci.org/browse/JENKINS-33886
* https://issues.jenkins-ci.org/browse/JENKINS-34121
@reviewbybees, @akshayabd and @stephenc
> [Docs] - Noting JENKINS-37302, JENKINS-33886, and JENKINS-34121 in JNLP3 Errata

- src/main/java/hudson/remoting/Channel.java
This is an aggregated PR, cleans up the class implementation
https://github.com/jenkinsci/remoting/commit/0d8a2af7cffa6aa5a6f2675e810b286a984af04e also introduces the incompatible change of Ref#clear(), but it's fine this the class is package-internal
@reviewbybees, esp. @stephenc as a creator of this class
> Cleanup hudson.remoting.Channel.Ref - NPE et al.

- src/main/java/hudson/remoting/ExportTable.java
This pull request just suppresses two issues in `ExportTable` implementation.
For discussion about caching or `Source` stacktraces:
* It is a legacy behavior introduced by @kohsuke in https://github.com/jenkinsci/remoting/commit/5db46de05db55262e75755ba47a99c4b12965d9b (remoting-2.40). 
* For every `object Deallocation` and `Reference Counter Increment` Remoting calculates the stacktrace and then also clones it. Implementation in `Throwable` is provided below
* The current behavior causes calculation and memory overheads, just to make heapdumps to provide more info
* I doubt we want this behavior to be enabled by default
Throwable implemetation:
```java
public StackTraceElement[] getStackTrace() {
return getOurStackTrace().clone();
}
private synchronized StackTraceElement[] …
```
> [JENKINS-37566] - FindBugs - Cleanup issues in ExportTable implementation

- src/main/java/hudson/remoting/ClassLoaderHolder.java
- src/main/java/hudson/remoting/DelegatingCallable.java
- src/main/java/hudson/remoting/DumbClassLoaderBridge.java
- src/main/java/hudson/remoting/ImportedClassLoaderTable.java
- src/main/java/hudson/remoting/PreloadJarTask.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/hudson/remoting/UserRequest.java
It appears that the target classloader in PreloadJarTask may be actually null. And FindBugs is grumbling about it. So I made an attempt to process the dependencies and to properly annotate methods and to catch possible edge cases.
The only real problem is that UserRequest#perform() may fail horribly if the request has been constructed with null classloader ref. So I have added explicit handling for this case on the invoking side.
@reviewbybees, esp. @kohsuke and @stephenc who are involved into this logic
> FindBugs - Unravel the classloading clew coming from the PreloadJarTask

- README.md
- docs/logging.md
- docs/workDir.md
- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/TeeOutputStream.java
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
- src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
This pull requests adds a basic support of workspaces to Remoting. It offers options, which allow enabling workspaces for JNLP and SSH agents in Jenkins. 
* In the original implementation we had no way to determine working directory on startup. Remoting itself didn't know about workspaces even if it was a Jenkins agent/slave
* With previous parameters the remoting behavior does not change
* The change will require additional configuration on the Jenkins side to enable workspaces by default
Scope of changes:
Potential improvements:
- Postponed: specifying workdir after the agent startup (let Jenkins enable it?)
- TBD: other magic to automagically determine Workdir in a compatible way
> [JENKINS-39370,JENKINS-39369] - Support of work directories in Remoting

- pom.xml
I have a hardware crypto key for signing remoting, hence the original available options are not enough for me. I decided to add more options, but it needs sign-off from @kohsuke that he still can sign the stuff with his key.
https://issues.jenkins-ci.org/browse/JENKINS-37567
@reviewbybees @kohsuke
> [JENKINS-37567] - Update maven Jar Signer and add provider/tsa options

- CHANGELOG-2.x.md
- CONTRIBUTING.md
- README.md
- docs/versions.md
- docs/workDir.md
Remoting 2.x has reached its end of life on May 01, 2017. My plan is to release new version if required, but I want to oficially call it as a deprecated version in order to avoid proactive backporting and to simplify documentation.
* What does it change for Jenkins project? 
* Nothing for weekly and LTS releases, Remoting is not used there anymore
* Nothing for the SECURITY team, the backporting process is different there
* What does change for Remoting 2.x users? 
* If you need an issue backporting, they will have to request it.
After the integration I will remove `stable-2.x` branch and start using `2.62.x` as we agreed with @jglick .
> Remoting 2.x End Of Life

- pom.xml
- src/main/java/hudson/remoting/Engine.java
- src/test/java/hudson/remoting/EngineTest.java
- src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerRule.java
- src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
The class was not covered by tests at all, so the issue has sneaked into the Remoting 3.8 release. `JNLPLauncher` test caught it in CI though. Added test + one-liner fix
https://issues.jenkins-ci.org/browse/JENKINS-44290
@reviewbybees
> [JENKINS-44290] - Prevent crash when starting Remoting agents in the default mode

- src/main/java/hudson/remoting/Launcher.java
Just a leftover from the previous fix, nulls are handled in hudson.remoting.Engine. I need to setup more end-to-end tests to capture such issues.
https://issues.jenkins-ci.org/browse/JENKINS-18578
@reviewbybees
> [JENKINS-18578] - Do not use the old cache when starting agents from CLI

- src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
I see this printed at the end of (passing) functional tests, which seems to be pure noise:
```
… hudson.util.ExceptionCatchingThreadFactory uncaughtException
WARNING: Thread Computer.threadPoolForRemoting [#1] terminated unexpectedly
java.nio.channels.ClosedSelectorException
at sun.nio.ch.SelectorImpl.keys(SelectorImpl.java:68)
at org.jenkinsci.remoting.protocol.IOHub.run(IOHub.java:422)
at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```
We were already handling this exception from various calls in the inner `try` block—but not from the …
> Handle ClosedSelectorException also from Selector.keys

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelBuilder.java
- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/JarCache.java
- src/main/java/hudson/remoting/Launcher.java
- src/test/java/hudson/remoting/EngineTest.java
It is an unreleased regression caused by me in https://github.com/jenkinsci/remoting/pull/166 . Filed it as [JENKINS-44973](https://issues.jenkins-ci.org/browse/JENKINS-44973).
Discovered it during testing the recent remoting version on SSH. Effectively launches with STDERR/STDOUT (SSH) and socket (tests) are failing now.
Also annotated all the things to prevent it in the future.
@reviewbybees
> [JENKINS-44973] - Ensure that JAR Cache management works correctly in Launcher

- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/ResourceImageInJar.java
- src/main/java/hudson/remoting/URLish.java
- src/main/java/hudson/remoting/Util.java
The NPE seems to be  non-realistic (why would RemoteClassloader construct URL from File?), but it’s better to fix it just in case.
https://issues.jenkins-ci.org/browse/JENKINS-37566
@reviewbybees
> [JENKINS-37566] - Annotate URLish methods and handle NPE in RemoteClassLoader.

- src/main/java/hudson/remoting/JarCache.java
- src/main/java/hudson/remoting/ResourceImageBoth.java
I firstly started from annotating the methods and throwing IOException, but then decided to do a proper error propagation instead. 
It smells like a real issue though there is no relevant bugtracker entries.
@reviewbybees
> Prevent NullPointerException in ResourceImageBoth if cannot initialize JAR retrieval

- pom.xml
Supersedes #171.
```
remoting$ mvn -Duser.name='big$mon\ey' validate -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Jenkins remoting layer 3.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:enforce (enforce-maven) @ remoting ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:display-info (display-info) @ remoting ---
[INFO] Maven Version: 3.5.0
[INFO] JDK Version: 1.8.0_131 normalized as: 1.8.0-131
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 4.10.0-22-generic
[INFO] 
[INFO] --- build-helper-maven-plugin:1.7:timestamp-property (timestamp-property) @ …
```
> [INFRA-1248] ${user.name} might contain metacharacters

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/CommandTransport.java
- src/main/java/hudson/remoting/ExportedClassLoaderTable.java
- src/main/java/hudson/remoting/MimicException.java
- src/main/java/hudson/remoting/MultiClassLoaderSerializer.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
- src/main/java/org/jenkinsci/remoting/nio/SelectableFileChannelFactory.java
Just a bulk change of annotations + some Javadoc, no behavior changes. Will submit a couple of other cases independently since they change to logic.
https://issues.jenkins-ci.org/browse/JENKINS-37566
@reviewbybees
> [JENKINS-37566] - Annotate methods which may explicitly return `null`

- src/main/java/hudson/remoting/Checksum.java
`DigestOutputStream` may change in the future, hence it worth to just refactor the code. I have not found annotations which would indicate that no closing it required for NullOutputStream. There are such warnings in the core as well OTOH
@reviewbybees
> [CID-156932] - Fix the imaginary resource leak in NullOutputStream

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/Request.java
Just noticed some issues in command execution logic...
@reviewbybees
> [JENKINS-45233] - Log errors when Response message cannot be delivered due to the closed channel

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelClosedException.java
- src/main/java/hudson/remoting/Request.java
- src/main/java/hudson/remoting/UserRequest.java
- src/main/java/hudson/remoting/VirtualChannel.java
- src/test/java/hudson/remoting/ChannelTest.java
This is a major update of Request execution logic in Remoting Channels, which should improve stability of the channel and prevent hanging of commands if the channel gets closed.
TODO:
Direct issue - [JENKINS-45023](https://issues.jenkins-ci.org/browse/JENKINS-45023). Many other issues should be addressed by it, I'd guess.
@reviewbybees @jglick @stephenc
> [JENKINS-45023] - Prevent execution of commands on closed or beingClosed channels

- pom.xml
- src/main/java/test/HelloGetResource.java
- src/main/java/test/HelloGetResourceAsStream.java
- src/main/java/test/HelloGetResources.java
This change adds an optional parameter, which disables file caching. My plan is to reuse it in Remoting tests in order to suppress some issues in Windows tests.
https://issues.jenkins-ci.org/browse/JENKINS-45349
@reviewbybees @jtnord
> [JENKINS-45349] - Test Client: Allow disabling file caching in HelloGetResource and HelloGetResources.

- docs/protocols.md
https://issues.jenkins-ci.org/browse/JENKINS-45841
> [JENKINS-45841] - Mark JNLP1/2 as deprecated in the documentation

- src/main/java/hudson/remoting/UserRequest.java
Linkage errors are a symptom of subtle classloading problems that are hart to investigate on its own. Propagating the exception upwards and over the channel only does not help as the stacktraces are dispersed all over the place (build logs, server log, discarded by caller, etc.) making the problem discovery and chain-of-the-events reconstruction harder.
I presume this is something of an interest for instance administrator so let's log it at one place.
> [JENKINS-46259] - Log all linkage errors during user requests

- pom.xml
It should finalize [JENKINS-37567](https://issues.jenkins-ci.org/browse/JENKINS-37567).
* See https://github.com/apache/maven-plugins/pull/125 and https://github.com/apache/maven-shared/pull/24
I have checked the default options, the change does not impact the local dev build and @kohsuke 's release flow. I am quite aware about the `jarsigner -tsa` step in the `release` profile, but it seems to be harmless on my local machine.
@reviewbybees @olamy @kohsuke
> [JENKINS-37567] - Add option to specify certchain, enforce certificate checks

- Jenkinsfile
It just does not make sense while [JENKINS-38696](https://issues.jenkins-ci.org/browse/JENKINS-38696) is not fixed
@reviewbybees
> [JENKINS-46341] - Disable Windows build for now

- src/main/java/hudson/remoting/Channel.java
- src/test/java/hudson/remoting/ChannelTest.java
https://issues.jenkins-ci.org/browse/JENKINS-46140
Implementing the variant `#1` mentioned in the issue.
> [FIXED JENKINS-46140] Improve presentation of remote exception

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelBuilder.java
- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/JarCache.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/ResourceImageBoth.java
- src/main/java/hudson/remoting/ResourceImageInJar.java
- src/main/java/org/jenkinsci/remoting/nio/NioChannelBuilder.java
- src/test/java/hudson/remoting/PrefetchingTest.java
It is a rework of my #167 fix for [JENKINS-44973](https://issues.jenkins-ci.org/browse/JENKINS-44973). During that fix I investigated a codebase and decided that it is better to make `Channel#jarCache` non-null to prevent misbehavior of agent initializers. But then we got a regression in the core, which was also initializing channels...
This fix makes the following adjustments:
I have not written a unit test for it, because it requires starting Jenkins or Remoting Test Client in an instance with non-writable home. I will do it once I have a better dockerized test framework for Remoting issues.
https://issues.jenkins-ci.org/browse/JENKINS-45755
@reviewbybess @recampbell @recena @Vlatombe
> [JENKINS-45755] - Make JARCache nullable in Channel

- pom.xml
Otherwise Javadoc is being generated twice, and then it is being uploaded twice. 
Common users have no package replace permissions in Artifactory, and the release just fails after that.
@reviewbybees @jglick
> Build Javadoc only once during the packaging phase.

- pom.xml
> Fix the Remoting 3.10.x release flow

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
It is a possible condition and just pollutes the logs
https://issues.jenkins-ci.org/browse/JENKINS-47425
@reviewbybees
> [JENKINS-47425] Do not print a stack trace on connection error

- pom.xml
Jacoc agent is quite heavy, and I see no reason in running it by default in any Remoting build.
This change moves the agent to an optional profile. It also picks the latest version, so IntellijIDEA is now able to read and show the `jacoco.exe` report.
@reviewbybees
> Update Jacoco to 0.7.9 and move it to the profile

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ImportedClassLoaderTable.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/test/java/hudson/remoting/ChannelTest.java
- src/test/java/hudson/remoting/PipeWriterTest.java
It is same as https://github.com/jenkinsci/remoting/pull/175, but for RPC Requests.
The idea is to prevent hanging of RPC Requests in edge cases when the channel goes down.
https://issues.jenkins-ci.org/browse/JENKINS-45294
@reviewbybees @jglick
> [JENKINS-45294] - RemoteInvocationHandler#RPCRequest is now a subject for channel status checks

- pom.xml
- src/main/java/hudson/remoting/Callable.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ClassLoaderHolder.java
- src/main/java/hudson/remoting/JarLoaderImpl.java
- src/main/java/hudson/remoting/Pipe.java
- src/main/java/hudson/remoting/ProxyOutputStream.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/RemoteInputStream.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/hudson/remoting/RemoteOutputStream.java
- src/main/java/hudson/remoting/RemoteWriter.java
- src/main/java/hudson/remoting/Request.java
- src/main/java/hudson/remoting/forward/ForwarderFactory.java
- src/main/java/hudson/remoting/forward/PortForwarder.java
- src/main/java/org/jenkinsci/remoting/SerializableOnlyOverRemoting.java
- src/test/java/hudson/remoting/ChannelFilterTest.java
- src/test/java/hudson/remoting/ChannelTest.java
- src/test/java/hudson/remoting/ClassFilterTest.java
- src/test/java/hudson/remoting/ClassRemotingTest.java
- src/test/java/hudson/remoting/PipeTest.java
- src/test/java/hudson/remoting/PrefetchingTest.java
- src/test/java/hudson/remoting/RemoteInvocationHandlerTest.java
- src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackImplTest.java
Discovered it during the experiments with #109
`Channel#current()` uses thread-local storage to determine the current channel. It returns null if the channel does not exist Some writeReplace/readObject/etc. serialization logic retrieves the channel in order to export the object via ExportTable. Obviously, such operations will fail if we try to serialize the object without Remoting context.
I propose to add a new interface to verify that serialization logic is being invoked for the remoting context and hence to avoid undesired NPEs.
https://issues.jenkins-ci.org/browse/JENKINS-47714
@reviewbybees @rysteboe @jglick @stephenc
> [JENKINS-47714] - Introduce SerializableOnlyOverRemoting and cleanup FindBugs in Channel#current().

- src/findbugs/excludeFilter.xml
- src/main/java/hudson/remoting/AbstractByteArrayCommandTransport.java
- src/main/java/hudson/remoting/Capability.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelBuilder.java
- src/main/java/hudson/remoting/Checksum.java
- src/main/java/hudson/remoting/ChunkedOutputStream.java
- src/main/java/hudson/remoting/ClassLoaderHolder.java
- src/main/java/hudson/remoting/DiagnosedStreamCorruptionException.java
- src/main/java/hudson/remoting/ExportTable.java
- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/InitializeJarCacheMain.java
- src/main/java/hudson/remoting/PipeWindow.java
- src/main/java/hudson/remoting/PreloadJarTask.java
- src/main/java/hudson/remoting/ProxyWriter.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/hudson/remoting/UserRequest.java
- src/main/java/hudson/remoting/Util.java
- src/main/java/hudson/remoting/Which.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
- src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
Addresses 17 issues in the library, mostly related to File operations, concurrency and NITs. 34 issues are still need to be fixed.
@reviewbybees and @stephenc hence some issues come from his code
> [JENKINS-37566] - FindBugs Cleanup. Part #1

- src/main/java/hudson/remoting/FileSystemJarCache.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/Util.java
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
- src/main/java/org/jenkinsci/remoting/util/PathUtils.java
It's a follow-up to #109 
https://issues.jenkins-ci.org/browse/JENKINS-47901
@reviewbybees @rysteboe . Also @stephenc since he was handling the same fun in the core
> [JENKINS-47901] - Stop using unchecked File#toPath()

- src/main/java/hudson/remoting/Channel.java
I was investigating the Channel synchronization logic and discovered that `Channel#setProperty()` and `Channel#getProperty` are inefficient in terms of the lock management. `Channel#properties` is a ConcurrentHashMap, and it does not need synchronization on its own.  The issue may be somehow contributing to the Channel instance deadlocks, but I see no strong evidence of that.
The only reason for synchronization is a wait()/nptifyAll() notification chain for `waitForProperty()`. I believe it needs to be reworked, but for now I just reduced the synchronization scope to these two calls.
It also cleans up the FindBugs issue.
> Performance: Reduce scope of Channel instance locks by property management

- src/test/java/hudson/remoting/UtilTest.java
On Windows you CAN create such directories.
But it does not mean we should try it even in tests.
Ideally the test needs to be rewritten or removed at all.
@reviewbybees @jtnord
> [JENKINS-38696] - huson.remoting.UtilTest#mkdirs() should not try creating global paths on Windows.

- src/main/java/hudson/remoting/Launcher.java
IIUC it may prevent Java Web Start agents from starting up in Java 9.
Anyway, the reflection is not required anymore since Remoting requires Java 8
https://issues.jenkins-ci.org/browse/JENKINS-46724
@reviewbybees @rysteboe @MarkEWaite @batmat
> [JENKINS-46724] - Get rid of the illegal Reflective operation in Launcher's checkTty()

- src/main/java/hudson/remoting/RemoteClassLoader.java
Remoting now required Java 8, so this Java 6 compatibility logic is not required at all.
Getting some extra performance is not bad as well.
https://issues.jenkins-ci.org/browse/JENKINS-46724
@reviewbybees @MarkEWaite @rysteboe @batmat
> [JENKINS-46724] - Remove obsolete ClassloadingLock reflection in RemoteClassloader.

- src/main/java/org/jenkinsci/remoting/engine/ChannelCiphers.java
- src/main/java/org/jenkinsci/remoting/engine/EngineUtil.java
- src/main/java/org/jenkinsci/remoting/engine/HandshakeCiphers.java
- src/main/java/org/jenkinsci/remoting/engine/Jnlp3ConnectionState.java
- src/main/java/org/jenkinsci/remoting/engine/Jnlp3Util.java
- src/test/java/org/jenkinsci/remoting/engine/JnlpProtocolHandlerTest.java
The protocol is deprecated, I would like to explicitly advice against using its classes internally and externally.
@reviewbybees @rysteboe @akshayabd
> Explicitly deprecate and Restrict JNLP3 utility classes.

- src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
This is not a part of the production code, but I use it sometimes. Reflection is not really required when you run with Oracle JDK / OpenJDK.
In longer term I am going to refactor the Remoting repository structure, so this code will be more explicit and documented in Developer guides.
@reviewbybees @stephenc @rysteboe
> Tests: Avoid using reflection in HandlerLoopbackLoadStress for CPU stats when possible.

- src/test/java/hudson/remoting/PrefetchingTest.java
It's a bit weird, but the test uses real classloader, which keeps the files open.
Ideally the tests needs to be fixed in order to stop keeping handlers in JVM when loading JARs (I started doing it for Remoting test client in RTC 1.1), but it's not the top priority right now.
@reviewbybees @jtnord
> [JENKINS-38696] - Do not delete temporary files in Windows in PrefetchingTest.

- src/main/java/org/jenkinsci/remoting/engine/HandshakeCiphers.java
- src/main/java/org/jenkinsci/remoting/engine/Jnlp3Util.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol3Handler.java
- src/main/java/org/jenkinsci/remoting/engine/LegacyJnlpConnectionState.java
- src/main/java/org/jenkinsci/remoting/protocol/ProtocolLayer.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayer.java
- src/main/java/org/jenkinsci/remoting/util/ByteBufferUtils.java
- src/main/java/org/jenkinsci/remoting/util/Charsets.java
- src/test/java/hudson/remoting/ChecksumTest.java
- src/test/java/hudson/remoting/FileSystemJarCacheTest.java
- src/test/java/org/jenkinsci/remoting/engine/ChannelCiphersTest.java
- src/test/java/org/jenkinsci/remoting/engine/EngineUtilTest.java
- src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
- src/test/java/org/jenkinsci/remoting/engine/Jnlp3UtilTest.java
- src/test/java/org/jenkinsci/remoting/engine/JnlpProtocolHandlerTest.java
- src/test/java/org/jenkinsci/remoting/util/ByteBufferQueueInputStreamTest.java
- src/test/java/org/jenkinsci/remoting/util/ByteBufferQueueOutputStreamTest.java
- src/test/java/org/jenkinsci/remoting/util/FastByteBufferQueueInputStreamTest.java
Remoting is on Java 8, so we can start using StandardCharsets from Java 7
@reviewbybees
> Cleanup usages of the custom Charsets class.

- src/main/java/hudson/remoting/Callable.java
- src/main/java/hudson/remoting/ChannelClosedException.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/hudson/remoting/forward/PortForwarder.java
- src/main/java/org/jenkinsci/remoting/ChannelStateException.java
- src/test/java/hudson/remoting/ChannelTest.java
- src/test/java/hudson/remoting/ClassRemotingTest.java
- src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackImplTest.java
This change introduces new API, which is expected to cleanup FindBugs reports in the core and to offer better diagnostics of edge cases.
The logic also allows failing fast when the channel is being terminated.
Downstream change: https://github.com/jenkinsci/jenkins/pull/3145
https://issues.jenkins-ci.org/browse/JENKINS-48055
@reviewbybees
> [JENKINS-48055] - Introduce convenient Channel retrieval methods in Callables.

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
- src/main/java/org/jenkinsci/remoting/util/https/NoCheckHostnameVerifier.java
- src/main/java/org/jenkinsci/remoting/util/https/NoCheckTrustManager.java
It is an attempt to improve https://github.com/jenkinsci/remoting/pull/205 and to reuse existing code from @stephenc . Originally the HTTPs certificate validation has been done in `hudson.remoting.Launcher`, but it was missing in `hudson.remoting.jnlp.Main`. So it was not possible to start a Java Web Start agent in the insecure mode. In https://github.com/jenkinsci/remoting/pull/205 @MattLud needs that.
How does it work now?
* When `-disableHttpsCertValidation` is passed from `Main`, the JNLP Endpoint HTTPs cert verification is disabled.
* JNLP agent ('Launcher.java') also sets the flag when `-noCertificateCheck` is passed
I also did some refactoring in order to prevent code duplication.
@reviewbybees @MattLud @Wadeck
> Allow disabling HTTPs cert validation of JNLP endpoint when starting Remoting from Main

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Initial proposal - Let me know what sort of unit tests you'd like to see or if you want the whitespace changes reverted.
> Add insecure flag to allow bypassing SSL hostname verification and cert checks

- src/main/java/hudson/remoting/ProxyOutputStream.java
Just YAGNI, it does not help garbage collector much and actually makes it more complicated due to breaking the object chain.
@reviewbybees
> [JENKINS-37566] - Stop nullifying channel in ProxyOutputStream#finalize()

- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/UserRequest.java
The field is actually always serializable, but we cannot confirm it statically due to the reflection code.
I decided to just suppress it for now and to document the method.
> [JENKINS-37566] - FindBugs: Suppress serialization warning for UserRequest#classLoaderProxy.

- src/main/java/hudson/remoting/Channel.java
In the worst case it will cause looping within the loop, but it should be fine in the case of the current implementation. It also prevents the infinite lock when the channel closes and does not send notifyAll() properly.
@reviewbybees
> [JENKINS-37566] - FindBugs: Channel#waitForProperty() should use wait() with a timeout.

- src/test/java/org/jenkinsci/remoting/engine/JnlpProtocolHandlerTest.java
The change just records all `@Theory` parameters.
I am just digging into test hanging in CI, so some extra diagnostics would be helpful. #235 also contributes to that. Logger is required to synchronize with diagnostics messages. Off the notes, the tests still send lots of channel state warnings. likely the close order needs to be changed:
```
WARNING: Failed to send back a reply to the request hudson.remoting.Request$2@16f4695f
hudson.remoting.ChannelClosedException: channel is already closed
```
@reviewbybees @stephenc @rysteboe
> Log all Theory parameters in JnlpProtocolHandlerTest.

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/Command.java
- src/main/java/hudson/remoting/PipeWindow.java
- src/main/java/hudson/remoting/ProxyOutputStream.java
- src/main/java/hudson/remoting/ProxyWriter.java
- src/main/java/hudson/remoting/Request.java
- src/main/java/hudson/remoting/UnexportCommand.java
I noticed that `Command#createdAt` is being handled incorrectly in some cases, so I annotated the related methods and fixed FindBugs issues.
https://issues.jenkins-ci.org/browse/JENKINS-37566
@reviewbybees
> [JENKINS-37566] - Cleanup issues in Command#createdAt handling

- src/main/java/hudson/remoting/Callable.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelClosedException.java
- src/main/java/hudson/remoting/Request.java
- src/main/java/org/jenkinsci/remoting/ChannelStateException.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
ChannelStateException has not been released yet, so the API compatibility is not broken.
https://issues.jenkins-ci.org/browse/JENKINS-48133
@reviewbybees
> [JENKINS-48133] - ChannelClosedException and ChannelStateException now record channel name and info when possible.

- src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
The wrapper may decrease the performance a bit, but NioChannelHub is not being used in JNLP4 anyway. Ideally submissions should not use the selector tasks queue in such lame way, but it’s risky to change it to another executor service.
> [JENKINS-37566] - Suppress issue with non-serializable inner classes in NioChannelHub

- src/main/java/hudson/remoting/AtmostOneThreadExecutor.java
- src/main/java/hudson/remoting/JarCacheSupport.java
- src/main/java/hudson/remoting/SingleLaneExecutorService.java
- src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
- src/main/java/org/jenkinsci/remoting/util/ExecutorServiceUtils.java
- src/test/java/hudson/remoting/PipeTest.java
Background: I was analysing JIRA issues related to the NIOHub fatal channel termination causing massive disconnection of agents. It appears that the `SingleLaneExecutor` is not completely correctly used there...
TL;DR: A single packet sent to the channel with pending shutdown may cause the termination of all remoting channels in `JNLP1`, `JNLP2`, `CLI`, and `CLI2` protocols. `JNLP4` does not seem to be affected.
* When we receive the command in a particular `NioTransport`, message parts are are being submitted to its `SingleLaneExecutor` 
* If the executor service rejects the task (e.g. due to the pending shutdown), a runtime `RejectedExecutionException` is being thrown. E.g. [here](https://github.com/jenkinsci/remoting/blob/master/src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.jav …
> [JENKINS-48130] - Improve handling and diagnostics of RejectedExecutionException in the code

- src/main/java/hudson/remoting/RemoteClassLoader.java
The case is well described by Thomas Maslen in https://issues.jenkins-ci.org/browse/JENKINS-37670. `UnsupportedClassVersionError` inherits `ClassFormatError`, so there should be no issues in any downstream code.
> [JENKINS-37670] - RemoteClassLoader should throw UnsupportedClassVersionError when the bytecode is not supported

- src/main/java/hudson/remoting/Channel.java
Just rebalances the code a bit, which may helpful if waitForProperty() waits for the channel lock too long and it gets closed.
> [JENKINS-37566] - FindBugs: Prevent the unconditional wait warning in Channel#waitForProperty()

- src/main/java/hudson/remoting/AsyncFutureImpl.java
**TL;DR**: A large part of Jenkins’ get-with-timeout logic is a subject for improper exit before the timeout.
It happens, because "wait(timeout)" is not in the loop. Object#wait(long) is explicit about that: "A thread can also wake up without being notified, interrupted, or timing out, a so-called spurious wakeup. While this will rarely occur in practice, applications must guard against it by testing for the condition that should have caused the thread to be awakened, and continuing to wait if the condition is not satisfied. In other words, waits should always occur in loops..."
https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#wait-long-
Impact:
* AsyncFutureImpl is being used explicitly in JarCacheSupport. Jar resolution with a timeout may fail due to the issue
* The class …
> [JENKINS-48309] - Prevent TimeoutException in AsyncFutureImpl in the case of spurious wakeups

- Jenkinsfile
- src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
Windows implementation of NIO Channel Selector does not request "Select now" in https://github.com/jenkinsci/remoting/blob/6165d6fb6a71a7f4fce52ce5fc4cac479052ce04/src/main/java/org/jenkinsci/remoting/protocol/IOHub.java#L436 and hence calls selector#select()... and this method has no timeout.
When the code gets into this branch, Selector will be waiting infinitely without calling selector#isOpen(). Such implementation relies on the Selector implementation, which shout interrupt the select() wait if the selector is being closed. But apparently it does not on my machine (Win 10, amd64, Oracle JDK 8u131)
This change adds wait timeout and makes the IOHub implementation to loop in the logic.
https://issues.jenkins-ci.org/browse/JENKINS-47965
@reviewbybees @stephenc @jtnord
> [JENKINS-47965, JENKINS-38696] - IOHub should not wait infinitely for Selector in Windows.

- Jenkinsfile
- pom.xml
Jenkins Remoting is now FindBugs-clean.
@reviewbybees @rysteboe + @rtyler since I have patched the Jenkinsfile
> [FIXED JENKINS-37566] - Enforce FindBugs by default and add it to Jenkinsfile

- src/main/java/hudson/remoting/ClassFilter.java
- src/test/java/hudson/remoting/ClassFilterTest.java
[JENKINS-47736](https://issues.jenkins-ci.org/browse/JENKINS-47736)
@reviewbybees
> [JENKINS-47736] Introduced ClassFilter.setDefault

- src/test/java/hudson/remoting/ChannelTest.java
Noticed when compiling:
```
Compiling 106 source files to …/remoting/target/test-classes
hudson/remoting/ChannelTest.java:[29,23] sun.rmi.runtime.Log is internal proprietary API and may be removed in a future release
hudson/remoting/ChannelTest.java:[29,23] sun.rmi.runtime.Log is internal proprietary API and may be removed in a future release
hudson/remoting/ChannelTest.java:[29,23] sun.rmi.runtime.Log is internal proprietary API and may be removed in a future release
```
@reviewbybees
> Remove unused imports

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ClassFilter.java
- src/test/java/hudson/remoting/ChannelFilterTest.java
Partial improvement for [JENKINS-49027](https://issues.jenkins-ci.org/browse/JENKINS-49027). For example, update https://github.com/jenkinsci/pipeline-aws-plugin/pull/37 to use a snapshot of `remoting` and comment out the whitelist entry. Without this change, you get
```
java.lang.SecurityException: Rejected: java.lang.String$CaseInsensitiveComparator
at hudson.remoting.ClassFilter.check(ClassFilter.java:75)
at hudson.remoting.MultiClassLoaderSerializer$Input.resolveClass(MultiClassLoaderSerializer.java:129)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1863)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1746)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2037)
at …
```
> [JENKINS-49027] Better report JEP-200 violations in Remoting

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
https://issues.jenkins-ci.org/browse/JENKINS-48561
> [FIXED JENKINS-48561] Give precedence to proxy exclusion list system property over env var

- src/main/java/hudson/remoting/AbstractByteArrayCommandTransport.java
- src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
- src/main/java/hudson/remoting/AbstractSynchronousByteArrayCommandTransport.java
- src/main/java/hudson/remoting/Capability.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelBuilder.java
- src/main/java/hudson/remoting/ClassFilter.java
- src/main/java/hudson/remoting/MultiClassLoaderSerializer.java
- src/main/java/hudson/remoting/UserRequest.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
- src/main/java/org/jenkinsci/remoting/util/AnonymousClassWarnings.java
[JENKINS-49994](https://issues.jenkins-ci.org/browse/JENKINS-49994)
@reviewbybees
> [JENKINS-49994] Infrastructure for warning about serialization of anonymous inner classes

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ImportedClassLoaderTable.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/hudson/remoting/Request.java
- src/test/java/hudson/remoting/ChannelTest.java
- src/test/java/hudson/remoting/PipeWriterTest.java
While trying to diagnose poor performance of a plugin which did heavy remote class loading in a dev build, I saw agent thread dumps such as
```
"pool-…-thread-… for channel id=… / waiting for channel id=…" … RUNNABLE
at java.lang.Throwable.getStackTraceElement(Native Method)
at java.lang.Throwable.getOurStackTrace(Throwable.java:827)
-  locked hudson.remoting.Command$Source@…
at java.lang.Throwable.writeObject(Throwable.java:979)
-  locked hudson.remoting.Command$Source@…
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128)
at …
```
> Disable recordCreateAt from RemoteClassLoader

- src/main/java/hudson/remoting/Engine.java
This PR is to solve newbie-friendly issue in https://issues.jenkins-ci.org/browse/JENKINS-49618.
> [JENKINS-49618] - Display Remoting version in the agent log when starting up the agent

- src/main/java/hudson/remoting/Capability.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/UserRequest.java
[JENKINS-50237](https://issues.jenkins-ci.org/browse/JENKINS-50237)
Inspired by https://github.com/jenkinsci/workflow-api-plugin/pull/64, but more complicated in this case since
* we prefer to retain the original exception type when possible
* we cannot be sure that the remote side is running a similarly updated Remoting
> [JENKINS-50237] When returning an exception to a UserRequest, always include a ProxyException

- src/main/java/hudson/remoting/UserRequest.java
Current code logs `INFO: %s class '%s' using classloader: %s` if system property `hudson.remoting.RemoteClassLoader.force` is set.  This is ugly and unhelpful.
The code (introduced in #82) should be using `java.text.MessageFormat.format` syntax but is (mistakenly) using `String.format` syntax instead.
I've checked the (new) log format locally (manually, as there's no unit-test for this code) and confirmed that the new format strong would log a message of the form `INFO: Loaded class 'com.foo.Bar' using classloader: com.foo.SomeClassLoader`.
> [JENKINS-50965] Fix log message

- src/test/java/org/jenkinsci/remoting/protocol/IOBufferMatcher.java
- src/test/java/org/jenkinsci/remoting/protocol/IOBufferMatcherLayer.java
- src/test/java/org/jenkinsci/remoting/protocol/impl/NetworkLayerTest.java
This test has been doing essentially the same thing over and over in a very repetitive way. Some slight, but pretty meaningless variations. And a whole bunch of absolute repetitions.
It kind of halfway used theories to reduce duplication, though it still used traditional duplication structures. And the theories mostly ended up just doing the same thing, as far as the Remoting specific code was concerned.
Ultimately, these repetitions were testing whether Java and the JVM works properly. Oddly and unfortunately, the answer is no, in this case. There are indications that issues exist, on certain platforms, in some extreme scenarios. Key among the scenarios is a very rapid creation and teardown of channels, file descriptors, or possibly most significantly pipes. This seems to particularly …
> [JENKINS-51378] Simplify NetworkLayerTest, removing duplication.

- src/main/java/hudson/remoting/CommandTransport.java
- src/main/java/hudson/remoting/JarCache.java
- src/main/java/hudson/remoting/SynchronousCommandTransport.java
JIRA task: https://issues.jenkins-ci.org/browse/JENKINS-51551
While working on the design for [JENKINS-51413](https://issues.jenkins-ci.org/browse/JENKINS-51413), I need to implement a new command transport to support Kafka communication. However, `CommandTransport` and `SynchronousCommandTransport` are not allowed to be sub-typed outside of the package because some of the fields, methods were made package-private. The proposed solution to this is to change them to protected access level.
@jenkinsci/code-reviewers @oleg-nenashev @jeffret-b @dwnusbaum @Supun94
> [JENKINS-51551] Allow CommandTransport and its sub-classes to be sub-typed from outside

- src/main/java/hudson/remoting/Request.java
- src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
Noticed a bunch of stack traces during `io.jenkins.plugins.artifact_manager_jclouds.NetworkTest#unrecoverableExceptionArchiving` (https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/41) for example, but really these have been irritating me for a long time (years?):
```
WARNING	hudson.remoting.Request$2#run: Failed to send back a reply to the request hudson.remoting.Request$2@…
Command Close created at
at hudson.remoting.Command.<init>(Command.java:65)
at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1265)
at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1263)
at hudson.remoting.Channel.close(Channel.java:1436)
at hudson.remoting.Channel.close(Channel.java:1403)
at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1270)
Caused: …
```
> Suppress some irrelevant stack traces

- src/main/java/hudson/remoting/ChannelBuilder.java
Just a follow-up to @jglick 's review comment in https://github.com/jenkinsci/jenkins/pull/3489
Nulls are fine according to the logic
> Annotate ChannelBuilder#header

- docs/configuration.md
- a comma was added between two TDs
@oleg-nenashev @reviewbybees
> Avoid the configuration.md table to be broken

- src/main/java/hudson/remoting/AbstractByteArrayCommandTransport.java
- src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
- src/main/java/hudson/remoting/AbstractSynchronousByteArrayCommandTransport.java
- src/main/java/hudson/remoting/ClassicCommandTransport.java
- src/main/java/hudson/remoting/Command.java
- src/main/java/hudson/remoting/CommandTransport.java
Remoting Kafka Plugin implements its own Command Transport, which creates Command Instances. Proper deserialization of Commands requires setting proper classloader and a local channel instances.
There is a Command#readFrom() method which does it, but it's package-private. Also, a construction of the ObjectInputStreamEx requires package-private Channel fields.
I propose to create a public Channel#readFrom(Channel, byte[] payload) method so that it can be used externally
Reference implementation: https://github.com/pvtuan10/remoting-kafka-plugin/pull/1
@pvtuan10
> [JENKINS-51841] - Offer a method for standardized command deserialization from the channel

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
In same configuration of balancer or firewall Jenkins HTTP/HTTPS port available for slave, but JNLP port is not visible for slave.
> [JENKINS-51818] Add JNLP port availability check

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
This is a fix for the [JENKINS-52204](https://issues.jenkins-ci.org/browse/JENKINS-52204) regression in Remoting 3.22 and Jenkins 2.129. When `-tunnel` option is set, Jenkins may be connecting to different host. So it does not make much sense to verify port availability in that case.
The issue comes from #275 . Although I believe that the current `-tunnel` behavior is rather obsolete and should be reworked/removed ([JENKINS-52246](https://issues.jenkins-ci.org/browse/JENKINS-52246)), I propose to just disable the check and restore compatibility for now
CC @denami @jeffret-b @dwnusbaum
> [JENKINS-52204] - Skip port availability check when -tunnel option is set

- pom.xml
Allow it to run in unattended mode on MacOS with GPG.
Without this addition, it gives an error that looks like this:
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
This is kind of a weird, complicated situation. 
With the existing pom configuration, the GPG signing step under the release profile fails because of the above error. 
This change passes a command-line argument to the GPG program, which allows the maven-gpg-plugin to pass the passphrase to GPG and succeed. The passphrase can be set via property in the maven system.xml, as demonstrated here: https://gist.github.com/michaelajr/ff4693bce9fc20e5200b34683aa4ba51 . Besides setting it in the servers section as demonstrated there it is also possible to set it in the properties …
> Add pom configuration to gpg plugin.

- CHANGELOG.md
See [JENKINS-53290] (https://issues.jenkins-ci.org/browse/JENKINS-53290)
For 3.24 and 3.25. I forgot to get back to update the changelog after the security release.
> [JENKINS-53290] Update changelog for last two releases.

- src/main/java/hudson/remoting/ProxyOutputStream.java
- src/main/java/hudson/remoting/ProxyWriter.java
See [JENKINS-42533](https://issues.jenkins-ci.org/browse/JENKINS-42533)
In rare cases, the Unexport command gets a little out of sequence and attempts to unexport an object that has already been unexported. It logs this at SEVERE level, when there is no indication of any harm. The issue is marked as minor.
Implement the fix in a similar pattern to [JENKINS-22853](https://issues.jenkins-ci.org/browse/JENKINS-22853), as noted in the PR. That fix reduced the log level for a similar message coming from the EOF command. As with that fix, it is unclear how to create a meaningful test, particularly as it is only a log level change..
> Fix [JENKINS-42533] Trying to unexport already unexported object

- src/main/java/org/jenkinsci/remoting/util/AnonymousClassWarnings.java
Recently noticed this complaining about a class in `credentials` plugin, and found that the warning was spurious in that case.
> [JENKINS-52945] AnonymousClassWarnings should not warn about enums

- src/main/java/hudson/remoting/JarLoaderImpl.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
Fixes a bug in #204: the JAR loaded statistic was being triggered (AFAICT) every time the remote side wanted to use some JAR, even if it was in the local JAR cache and did not actually need to be sent.
> Channel.notifyJar was being called too often

- src/main/java/hudson/remoting/SynchronousCommandTransport.java
Observing a lot of these in Evergreen coming from the `docker` plugin. Not actionable by developers (probably).
> Downgrade error messages from SynchronousCommandTransport

- src/main/java/org/jenkinsci/remoting/protocol/ProtocolStack.java
See [JENKINS-53569](https://issues.jenkins-ci.org/browse/JENKINS-53569) for a description of the deadlock, including stack traces of the deadlocked threads.
There is no indication that this section of code constitutes a critical section. The only meaningful thing it does is atomic and is handled elsewhere in the code by good design. The extra checks serve no significant purpose.
The code in Filter that calls this grabs a lock on Filter before it calls this meaning that it already holds one lock. If another thread grabs the lock on ProtocolStack before the Filter than a thread is always possible. Locking occurs too frequently without a strategy for preventing deadlock.
Locking is complex enough without abusing locks in weird ways.
@reviewbybees
> [JENKINS-53569] Remove unnecessary locking.

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ExportTable.java
See [JENKINS-54005](https://issues.jenkins-ci.org/browse/JENKINS-54005)
See also a previous PR, #283, which downgraded the message severity of an extremely similar message on related paths.
In rare cases, the Unexport command gets a little out of sequence and attempts to unexport an object that has already been unexported. It logs this at SEVERE level, when there is no indication of any harm. The issue is marked as minor.
Like that one and the one before it, this PR reduces the log level to remove the unnecessarily severe message.
Again, it is unclear how to create a meaningful test, particularly as it is only a log level change.
> [JENKINS-54005] Another instance of an unnecessarily severe warning.

- src/main/java/hudson/remoting/ChannelBuilder.java
See [JENKINS-47977](https://issues.jenkins-ci.org/browse/JENKINS-47977)
If we cannot create create the jar cache, leave it null.
In some cases, the default jar cache directory may not be writeable, which will cause
an IO exception trying to create the cache. Fail a bit more gracefully by running without a cache. This seems to be a supported configuration by the code. Further, the user can specify a jar cache location.
@oleg-nenashev, did you have any different ideas on how to deal with this one?
> [JENKINS-47977] Jenkins build fails with Root directory not writable

- src/main/java/hudson/remoting/forward/ForwarderFactory.java
- src/main/java/hudson/remoting/forward/PortForwarder.java
- src/test/java/hudson/remoting/ClassFilterTest.java
- src/test/java/hudson/remoting/DeadRemoteOutputStreamTest.java
- src/test/java/hudson/remoting/PipeTest.java
- src/test/java/hudson/remoting/PipeWriterTest.java
- src/test/java/hudson/remoting/PrefetchingTest.java
- src/test/java/hudson/remoting/ProxyWriterTest.java
- src/test/java/hudson/remoting/throughput/Sender.java
- src/test/java/org/jenkinsci/remoting/nio/SocketClientMain.java
See [JENKINS-49987](https://issues.jenkins-ci.org/browse/JENKINS-49987)
Convert them to static, named classes. These are ones that I was easily able to locate relating to Callable. After these changes, the warnings no longer show up during Remoting build tests.
@oleg-nenashev Are there any concerns with this about compatibility or over-the-wire format changes?
> [JENKINS-49987] Clean up warnings about anonymous callable.

- docs/configuration.md
- docs/no_proxy.md
- pom.xml
- src/main/java/hudson/remoting/NoProxyEvaluator.java
- src/main/java/hudson/remoting/Util.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
- src/test/java/hudson/remoting/NoProxyEvaluatorTest.java
- src/test/java/hudson/remoting/UtilTest.java
See [JENKINS-48778](https://issues.jenkins-ci.org/browse/JENKINS-48778)
We've had several issues submitted against the no_proxy implementation in Remoting. We resolved one a couple of months ago. Implementing that one turned out to be harder and less clean than it needed to be. As I started working on this one, I realized the area could use some restructuring, improved capabilities, and better documentation.
Unfortunately, there isn't a single standard or reference on how no_proxy should behave. Implementations and rules vary by application or system. I modeled this proposal after [this](https://github.com/golang/go/issues/16704#issuecomment-312502347) well-researched proposal for Go. There are a few differences.
This new version should retain all existing capabilities. If something …
> [JENKINS-48778] Re-work the implementation of the no_proxy capability.

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ProxyOutputStream.java
At least suppresses the visible error in [JENKINS-54566](https://issues.jenkins-ci.org/browse/JENKINS-54566).
> [JENKINS-54566] Ignore attempts to flush a ProxyOutputStream which has already been finalized

- src/main/java/hudson/remoting/RemoteClassLoader.java
I suspect the root cause of
```
java.lang.LinkageError
at hudson.util.ProcessTree$UnixReflection.<clinit>(ProcessTree.java:710)
at hudson.util.ProcessTree$Unix.get(ProcessTree.java:578)
at hudson.util.ProcessTree.killAll(ProcessTree.java:145)
at hudson.Proc$LocalProc.destroy(Proc.java:384)
at hudson.Proc$LocalProc.kill(Proc.java:376)
at com.cloudbees.opscenter.server.jnlp.controller.JnlpSlaveControllerImpl.kill(JnlpSlaveControllerImpl.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
Caused by: java.lang.ClassNotFoundException: Classloading from system classloader disabled
at hudson.remoting.RemoteClassLoader$ClassLoaderProxy.fetch4(RemoteClassLoader.java:854)
at hudson.remoting.RemoteClassLoader$ClassLoaderProxy.fetch3(RemoteClassLoader.java:8 …
```
> Better diagnostics for errors from RemoteClassLoader.fetch4

- pom.xml
- src/main/java/hudson/remoting/NoProxyEvaluator.java
- src/main/java/org/jenkinsci/remoting/org/apache/commons/net/util/SubnetUtils.java
- src/main/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/InetAddressValidator.java
- src/main/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/RegexValidator.java
- src/test/java/org/jenkinsci/remoting/org/apache/commons/net/util/SubnetUtilsTest.java
- src/test/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/InetAddressValidatorTest.java
- src/test/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/RegexValidatorTest.java
Tweak the implementation to not draw in new dependencies.
For the changes to the no_proxy capability, I added a couple of dependencies for checking and handling ip addresses and subnets.
One of them was clearly the wrong one to use when I started integrating.
Rather, than add dependencies, we decided to copy in utilities. This same pattern was followed recently in Jenkins core to avoid introducing new dependencies into Jenkins core that plugins may become dependent on.
> [JENKINS-48778] Refactoring earlier unreleased implementation.

- src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
https://github.com/jenkinsci/jenkins/pull/3804/commits/f966a8917046c5fc1f31ed109f7d9333278135d2 caught [this](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-3804/3/artifact/test/target/surefire-reports/2018-12-12T14-11-05_283-jvmRun1.dumpstream/*view*/):
```
Corrupted stdin stream in forked JVM 1. Stream 'Both error and output logs will be printed to /mnt/agent-workspace/workspace/Core_jenkins_PR-3804-BDA3623DFIXRNF67IWW63OZ647EEFX6OR7LH5CV7JUQJB5ANAMKA/test/target/test/remoting'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'Both error and output logs will be printed to /mnt/agent-workspace/workspace/Core_jenkins_PR-3804-BDA3623DFIXRNF67IWW63OZ647EEFX6OR7LH5CV7JUQJB5ANAMKA/test/target/test/remoting'.
at …
```
> Avoid System.out/err.println in anything that might be called from a Surefire JVM

- src/main/java/hudson/remoting/Launcher.java
Launcher was never passing the loggingConfigFilePath to the workDirManager
so the -loggingConfig setting didn't work.
https://issues.jenkins-ci.org/browse/JENKINS-51004
> [JENKINS-51004] - Pass loggingConfigFilePath from CLI arguments to the workDirManager

- src/main/java/hudson/remoting/jnlp/Main.java
See size check below, and the indexing inside `createEngine`. Not sure how long this Javadoc has been wrong. Perhaps it would be better to use
```java
@Argument(index = 0) public String secretKey;
@Argument(index = 1) public String agentName;
```
but I will leave that for another day.
> Incorrect Javadoc for Main.args

- src/main/java/hudson/remoting/Launcher.java
Revert #193 because of issues it introduced with some cloud agent scenarios. See [JENKINS-57713](https://issues.jenkins-ci.org/browse/JENKINS-57713).
If someone wants to try again to address [JENKINS-46515](https://issues.jenkins-ci.org/browse/JENKINS-46515) without introducing problems for other scenarios they are welcome to propose a new PR.
After merging this change to remove the earlier one, I plan on releasing a new version of Remoting with other changes.
> [JENKINS-57713] Revert [JENKINS-46515] / PR 193

- src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
While debugging an unrelated issue, I noticed a typo in a common log statement ("staring" instead of "starting"). I fixed that, and also replaced "info" with the more proper "information" (and added a period to the sentence).
> Fix typo in Selector wakeup thread messages

- src/main/java/hudson/remoting/jnlp/Main.java
After an attempted upgrade of args4j in jenkinsci/swarm-plugin#120, the following exception was thrown:
```
java.lang.IllegalStateException: Cannot set value to a final field 'hudson.remoting.jnlp.Main.urls'.
at org.kohsuke.args4j.spi.Setters.create(Setters.java:32)
at org.kohsuke.args4j.ClassParser.parse(ClassParser.java:34)
at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:96)
at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:71)
at hudson.remoting.jnlp.Main._main(Main.java:215)
at hudson.remoting.jnlp.Main.main(Main.java:188)
at hudson.plugins.swarm.SwarmClient.connect(SwarmClient.java:325)
at hudson.plugins.swarm.Client.run(Client.java:193)
at hudson.plugins.swarm.Client.main(Client.java:130)
```
As of args4j 2.32, "[final fields can no longer be …
> [JENKINS-57959] Remove final from args4j fields

- pom.xml
- src/main/java/hudson/remoting/UserRequest.java
Updated the parent POM to [the latest version](https://github.com/jenkinsci/pom/releases), which has SpotBugs support, and migrated the annotations dependency from FindBugs to SpotBugs. This exposed the following new SpotBugs error:
```
[ERROR] Dead store to $L4 in hudson.remoting.UserRequest.perform(Channel) [hudson.remoting.UserRequest] At UserRequest.java:[line 171] DLS_DEAD_LOCAL_STORE
```
I fixed this by removing the unnecessary variable declaration and assignment.
> Switch to SpotBugs

- pom.xml
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
- src/main/java/org/jenkinsci/remoting/util/VersionNumber.java
- src/test/java/org/jenkinsci/remoting/util/VersionNumberTest.java
See #318. After I merged it into master, I discovered that Jenkins core won't build with this updated Remoting. The failure gives no information. I have tried various changes to get it to build but the only thing I've gotten to work is to remove the shading.
I should have squash-merged #318 and then I could just revert it, but since I didn't reverting is more complicated. I could still continue down that route, or use this proposal, which builds fine. I'm inclined to go ahead and move forward by merging this change in.
I haven't changed or updated `VersionNumber` and `VersionNumberTest` except to add a comment indicating where we copied them from and why.
> [JENKINS-50095] Fix version number issues in Jenkins core

- pom.xml
- src/main/java/hudson/remoting/jnlp/Main.java
Downstream of jenkinsci/remoting#326 (q.v. for an explanation of the main API change and the testing done). Depends on jenkinsci/jenkins#4063. Blocks jenkinsci/swarm-plugin#120.
> [JENKINS-57959] Bump args4j from 2.0.31 to 2.33

- CHANGELOG.md
Since there is at least a suggestion of a connection between updating the args4j dependency in Remoting and in core, I decided to put the dependency in its own release, so there are more options in how it can be included in core. We don't think there are any actual issues if they're not updated simultaneously, but I'm giving the opportunity for us to make this clean.
> Update changelog for version 3.33.

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
This pull request adds changes on top of https://github.com/jenkinsci/remoting/pull/286. The changes here implement the missing
> support of Instance Identity key so that JNLP4 protocol can be used
Connecting to a Jenkins without http port now already works. You can test it with the command below. 
```sh
java -cp slave.jar hudson.remoting.jnlp.Main \
-headless -noHttpEndpoint \
-tunnel <jenkinsHost>:<jnlpPort> \
-instanceIdentity <instanceIdentityString> \
<secretString> <agentName>
```
- The agent needs to be prepared on the master  - copy the name and secret.  
- The instanceIdentityString is the base64 encoded byte array of the masters Instance Identity. You can get it via `hudson.remoting.Base64.encode(org.jenkinsci.main.modules.instance_identity.InstanceIdentity.get().getPublic().getE …
> Addition to PR 286: Add Instance Identity Key to Support JNLP4

- src/findbugs/excludeFilter.xml
This filter is no longer needed since https://github.com/jenkinsci/remoting/pull/331/
> Remove FindBugs filter for hudson.util.VersionNumber

- src/main/java/hudson/remoting/Base64.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/Util.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpEndpointResolver.java
- src/test/java/hudson/remoting/BinarySafeStreamTest.java
Replaced existing base64 implementation with the one provided by java and deprecated the class.
Using the RFC 4648 encoder instead of the RFC 2045 encoder. The RFC 2045 encoder contains linefeeds unlike RFC 4648 which is what the current implementation does.
> [JENKINS-59047] - Use base64 from java

- src/main/java/org/jenkinsci/remoting/engine/HostPort.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointConfigurator.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
- src/test/java/org/jenkinsci/remoting/engine/HostPortTest.java
See [JENKINS-59094](https://issues.jenkins-ci.org/browse/JENKINS-59094)
Under some conditions, agents using tunneling have failed to connect after changes in the 3.34 Remoting release. I haven't been able to reproduce it or isolate it yet, but this change restores the host:port parsing logic to previous behavior for handling an empty port. At a minimum, this should at least get us past the exception. It may well solve the problem.
> [JENKINS-59094] Jenkins connection failure with tunneling

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
- Use input stream reader instead. The one situation I think this is different is that `readline()` from stream reader returns null on EOF but `EngineUtil.readline()` returns a blank string. I'm not sure if that matters but it seems like that behaviour masks issues.
EDIT: Turns out spotbugs complains about it so I throw an exception in the case the socket stream EOFs
> Remove engineutil usage

- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/Util.java
- src/main/java/hudson/remoting/jnlp/Main.java
Adds -version and a -help command line options.
> Add -version and -help

- CHANGELOG-2.x.md
- CHANGELOG.md
- README.md
- docs/configuration.md
- docs/logging.md
- docs/protocols.md
- docs/remoting-3-compatibility.md
- docs/tcpAgent.md
- docs/workDir.md
- src/main/java/org/jenkinsci/remoting/engine/HandshakeCiphers.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol1Handler.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol2Handler.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol3Handler.java
- src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
- src/test/java/hudson/remoting/TrafficAnalyzer.java
- src/test/java/org/jenkinsci/remoting/engine/HandshakeCiphersTest.java
Where possible remove the term "slave" from documentation, replacing with "agent" as needed. In some instances, both were used but we're past the time where we need to continue using the old name.
Removes from AsciiDoc pages, JavaDoc, and code comments.
The remaining documentation references are for external or remaining API references.
> Clean up "slave" term from documentation.

- src/main/java/org/jenkinsci/remoting/engine/HandshakeCiphers.java
A couple of internal usages that really didn't need to old name.
> Remove internal usages of "slave" term.

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
I'm not sure if we want to remove the term in these instances. It depends on what we consider the API and how much we prioritize removing the term "slave" vs. maintaining any possible library use.
Essentially the API at this point are the command-line parameters (the `@Option` tags) and the object fields are internal (though they have the access modifier `public`). Any integration that steps beyond the CLI parameters into the fields is deep and rare.
I'm inclined to think it's better to make this change and continue the removal of the disfavored term. How concerned are others about maintaining the existing API at this level?
> Remove some usages of slave from public fields.

- src/main/java/hudson/remoting/Engine.java
See [JENKINS-60926](https://issues.jenkins-ci.org/browse/JENKINS-60926).
A renaming of Engine.slaveName to Engine.agentName and making it
private broke a complicated interaction with the server and the slave-installer-module.
Rename just this one part back to get it working again.
The previously unknown usage is in [slave-installer-module](https://github.com/jenkinsci/slave-installer-module/blob/3f1fce8ddb1de41b280546755700c727311448b9/src/main/java/org/jenkinsci/modules/slave_installer/impl/InstallerGui.java#L142).
> [JENKINS-60926] Fix "Install as a service" on Windows.

- pom.xml
IntelliJ configured to use adoptopenjdk openj9 1.8 complains about:
https://github.com/jenkinsci/remoting/blob/ca2fbc659c5b2a899bbce6c22d3a0ff87c21de58/src/main/java/hudson/remoting/Engine.java#L70-L76
This appears to make it happy.
> Add javax.websocket to pom.xml

- src/main/java/hudson/remoting/Engine.java
- src/test/java/hudson/remoting/EngineTest.java
Different approach to earlier change. Keep the renaming and add a getter for other modules to use.
> [JENKINS-60926] Expose the agent name via a getter

- src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
- src/main/java/hudson/remoting/Engine.java
See [JENKINS-61409](https://issues.jenkins-ci.org/browse/JENKINS-61409).
Fixes support of websocket messages more than 64kb long.
See downstream https://github.com/jenkinsci/jenkins/pull/4596
> [JENKINS-61409] Websockets: Use AbstractByteBufferCommandTransport to transport messages

- src/main/java/hudson/remoting/Request.java
Looking at a thread dump, saw something like
```
"SupportPlugin periodic bundle generator: writing ….zip since …" …
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <…> (a java.util.concurrent.FutureTask)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
at java.util.concurrent.FutureTask.get(FutureTask.java:191)
at hudson.remoting.Request.call(Request.java:188)
- locked <…> (a hudson.remoting.UserRequest)
at hudson.remoting.Channel.call(Channel.java:956)
at hudson.FilePath.act(FilePath.java:1070)
at hudson.FilePath.act(FilePath.java:1059)
at hudson.FilePath.copyTo(FilePath.java:2234)
at com.cloudbees.jenkins.support.api.FilePathContent.writeTo(FilePath …
```
> Broaden the scope of Thread.name inclusion to whole Request.call body

- src/main/java/hudson/remoting/Launcher.java
- src/test/java/hudson/remoting/LauncherTest.java
- src/test/resources/hudson/remoting/embedded_doctype.jnlp
- src/test/resources/hudson/remoting/lol.jnlp
- src/test/resources/hudson/remoting/note.dtd
- src/test/resources/hudson/remoting/test.jnlp
- src/test/resources/hudson/remoting/xxe_file.jnlp
- src/test/resources/hudson/remoting/xxe_http.jnlp
This was improved during findsecbugs processing. Now that I've dug into it a little bit I'm adding some minor improvements. The findsecbugs documentation suggests two feature settings to resolve the issue. They both yield essentially the same result. This one is a little cleaner and more thorough.
Mostly, this change involves adding several tests to demonstrate the processing behavior. These aren't essential but they are good documentation.
> Minor JNLP parsing improving, mostly in testing

- src/main/java/hudson/remoting/DumbClassLoaderBridge.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/test/java/hudson/remoting/ClassRemotingTest.java
Some simple modernization and cleanup for RemoteClassLoader. These changes are all refactorings with no change in behavior.
Once I get this approved and merged I've got a couple more cleanup PRs to process and then some actual improvements to RemoteClassLoader.
> Cleanup and modernization for RemoteClassLoader

- pom.xml
This pull request is needed for https://github.com/jenkins-infra/release/pull/60/files, in order to use the same release workflow than jenkins core release.
Basically it configures the maven release plugin to not push commits (let that operation) done outside, and release based on local git repository
> [INFRA-2619] Add maven release plugin default setting

- pom.xml
This eliminates the need for a local configuration for findsecbugs.
> Update to use the latest parent pom.

- src/test/java/hudson/remoting/PrefetchTest.java
It inexplicably fails on the release CI but nowhere else. There is no indication why it fails.
The test does very little anyway and is not implicated in any known real failure or recent change.
The test is prefetching a jar. On my local machine it's grabbing it from my ".m2/respository" tree. On the release CI machine it appears to not be able to resolve its original location when it tries to set up the transfer.
> Disable a test for the release CI.

- pom.xml
According to the link https://issues.apache.org/jira/browse/MJARSIGNER-53, I observed that such issue had already been fixed. And based on the comment "Remove once it's in upstream". This override attribute is not needed.
The override attribute and comment:
https://github.com/jenkinsci/remoting/blob/0860f222f45802f0dab0e9e7a06e93be89baf687/pom.xml#L74-L75
> Remove an override attribute exists in pom.xml file since the related issue had been already fixed.

- src/main/java/hudson/remoting/Engine.java
Currently, if -webSocket is set and -url does not have a trailing slash, connection will fail with an UnresolvedAddressException. This can prove confusing to diagnose and resolve.
This PR adds a check for a trailing slash and adds it if missing.
> Add protection against missing trailing slashes when using websocket.

- src/main/java/hudson/remoting/RemoteInvocationHandler.java
See https://github.com/jenkinsci/jenkins/pull/4621 for the original buglet. As of https://github.com/jenkinsci/jenkins/pull/4912, seems better to just avoid the problematic idiom.
> RemoteInvocationHandler.reportStats LogRecord’s could get mangled during serialization

- src/main/java/hudson/remoting/Util.java
See [JENKINS-63118](https://issues.jenkins-ci.org/browse/JENKINS-63118)
In Util.makeResource(), call deleteDirectoryOnExit() on the temporary
directory, and not just on the resource file it contains.
> [JENKINS-63118] delete /tmp/resource-xxx on exit

- pom.xml
Also obtain the junit version from the parent.
jenkinsci/pom#138 in the parent pom means that argLine needs to be defined.
Define it as empty unless overridden.
This change supersedes #405 and #395.
> Update to the latest parent pom.

- pom.xml
- src/test/java/hudson/remoting/ClassRemotingTest.java
- src/test/java/hudson/remoting/PrefetchTest.java
Upgrade it to a currently supported version. The library has been majorly changed since the ancient version we've been using and has a new groupId and artifactId. 
We barely use it, only for a couple of very dubious tests. It isn't used in production at all. We've had to disable the one test because of unreliable results on different systems. Maybe it would be better to remove that test, but these simple changes do allow them to keep working as they best the are.
> Upgrade asm

- pom.xml
Upgrade both components together in one PR to preserve master as buildable.
Supersedes the dependabot PRs #404 and #400.
> Upgrade bouncy castle

- src/main/java/hudson/remoting/Launcher.java
It's time to remove the alias "-slaveLog" and only accept "-agentLog". It's been 4 years since "-slaveLog" was obsoleted as an alias and "-aliasLog" was made the correct term. It's possible that some people have continued to use the wrong term all that time, but at this point it's time to just remove the outdated term and make them update.
> Remove obsolete log alias.

- docs/inbound-agent.md
- src/main/java/hudson/remoting/jnlp/Main.java
- src/main/java/hudson/remoting/jnlp/package-info.java
This cleans up a few more instances of incorrect terminology in documentation.
This only fully makes sense with jenkinsci/jenkins#35452, but I consider the two to be fully independent. Without that change in core, the file name in the documentation here doesn't exist, but that's a minor concern as things get updated and coordinated. Old and new agents work fine with or without the core change.
> Improve documentation, removing more instances of 'slave' term.

- pom.xml
This started as a dependabot update but when I tried to kick CI again, the bot removed that PR. Here it's recreated as a self-standing change.
> Update maven-assembly plugin.

- pom.xml
- src/main/java/hudson/remoting/NoProxyEvaluator.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
The update is simple, but there's an interesting new findsecbugs pattern, IMPROPER_UNICODE. The behavior can be pretty devious. But, here we're getting the comparison values from the controller, hardcoded, or from the user/admin at launch. We have to trust these sources.
Alternatively we could drop the case-insensitive comparisons. It's possible that could cause a regression, though it's pretty unlikely.
Also update access-modifier-annotation to 1.21 in this PR because there's a dependency relationship via enforcer.
> Update to parent 1.63.

- src/main/java/org/jenkinsci/remoting/util/KeyUtils.java
Contrary to the conversation in #361, this method was already used in `remoting`, and it is used in https://github.com/jenkinsci/jenkins/pull/5044 since that was basically a copy & inline of this method.
> Undeprecate KeyUtils.fingerprint

- src/main/java/hudson/remoting/Engine.java
- src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
- src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackLoopbackLoadStress.java
- src/test/java/org/jenkinsci/remoting/protocol/cert/SSLContextRule.java
I suggest removing the hardcode with JKS Keystore to allow using other Keystores. For example, BCFKS provided in the FIPS version of Bouncy Castle.
More info here:
https://groups.google.com/g/jenkinsci-dev/c/YkEG_oSR1mw
> Remove hardcode of JKS for use other key stores

- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/test/java/hudson/remoting/ClassRemoting2Test.java
- src/test/java/hudson/remoting/ClassRemotingTest.java
- src/test/java/hudson/remoting/ForkRunner.java
- src/test/java/hudson/remoting/TestStaticGetResources.java
- src/test/java/hudson/remoting/TestStaticResourceReference.java
See [JENKINS-61103](https://github.com/jenkinsci/remoting/pull/372). This is an alternative approach to #372.
There have been a couple of previous efforts to introduce retries into the RemoteClassLoader. These have reportedly resolved some situations, however we have continued to receive reports of class loading failures. As noted in JENKINS-61103 and the earlier PR, one area that isn't covered by a retry is resource loading as part of a class.
This PR does three things:
1. Fixes some of the tests so that they work correctly. Some of them weren't really testing what they claimed to. Some could be simplified a little.
2. Introduces timeouts and sleep to the retries. This should slow down further attempts that may quickly fail and provide a way to eventually terminate if the problem doesn't …
> [JENKINS-61103] Retry on class resource load failures and introduce timeouts

- pom.xml
It causes related failures in Jenkins tests.
We can wait for the next update or try later to resolve the failures.
At this point, I just don't want to have this added complexity in this release.
(I could have just the revert feature, but since the change got in before other changes, I decided to do a regular PR to keep a record.)
> Undo the Dependabot proposed update for the Websocket library.

- pom.xml
https://github.com/jenkinsci/jenkins/pull/5292 was originally pointing to the parent pom's release notes
> Add url to fix dependabot release notes

- src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
- src/test/java/org/jenkinsci/remoting/protocol/IOBufferMatcher.java
- src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackLoopbackLoadStress.java
- src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayerTest.java
According to [this guide](https://github.com/krka/java8-future-guide), `SettableFuture.create()` can be replaced with Java 8's `new CompletableFuture()`. I did so for any test code that used `SettableFuture`. Note that modifying usages of `SettableFuture` in non-test code has binary compatibility implications, so I did not touch non-test code in order to eliminate any risk of regression.
> Migrate from SettableFuture to CompletableFuture in tests

- src/main/java/hudson/remoting/ExportTable.java
- src/test/java/hudson/remoting/ExportTableTest.java
Not certain if this is a good idea but the idea spawned from [JENKINS-63975](https://issues.jenkins.io/browse/JENKINS-63975) as stacktraces seem to take a considerable amount of memory usage in Jenkins and as far as I understand it, it is entirely for debugging.
Although I'm not certain how often this workflow is used in the real world, if its very rare this ever happens perhaps its better to disable by default.
> Disable stacktraces from ExportTable entries by default

- src/main/java/org/jenkinsci/remoting/protocol/ProtocolStack.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/BIONetworkLayer.java
See [JENKINS-63520](https://issues.jenkins.io/browse/JENKINS-63520).
Some users have reported a rare thread deadlock when starting an inbound TCP agent. There are no known reports of this occurring at other times. The reporter included a stack track showing information about the deadlock. It occurs when the agent ProtocolStack is still initializing and a message is received on the networking layer.
Personally, I've never observed the problem and have no way of testing it. I've tested normal behavior and this fix has worked fine.
This fix delays the processing of any received messages until after the ProtocolStack has fully initialized.
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/p] Ensure you have provided tests - that demonstrates feature works or …
> [JENKINS-63520] Sequence the startup and receiving to avoid a deadlock.

- README.md
Update the url of HudsonArch-Remoting.pdf, because hudson-ci.org cannot be accessed.
> Update the url of HudsonArch-Remoting.pdf

- src/main/java/hudson/remoting/Engine.java
I'm working on the ticket below for my first contribution to Jenkins!
[[JENKINS-40700] Display communication  protocol in agent logs](https://issues.jenkins.io/browse/JENKINS-40700)
As it is difficult to know the communication protocol from the established channel on the controller side, I propose holding the communication protocol name on the agent side. It is much simpler than holding it on the controller side.  
So, what I do here is
- Save the protocol name when the channel is established
- Create an endpoint to provide the protocol name
~I'll submit another PR that uses this feature on the controller side to [jenkinsci / jenkins](https://github.com/jenkinsci/jenkins) soon.~
I submitted the PR that uses this feature on the controller side to  [jenkinsci / …
> [JENKINS-40700] Enable current engine to hold the communication protocol

- src/main/java/hudson/remoting/Engine.java
See [JENKINS-57831](https://issues.jenkins.io/browse/JENKINS-57831). A more conservative version of #448.
During a recent Jenkins upgrade, one of my Swarm clients (which are started with `-deleteExistingClients` so that they can reconnect to Jenkins after a controller restart) failed to reconnect. Jobs then eventually hit the `org.jenkinsci.plugins.workflow.support.pickles.ExecutorPickle.timeoutForNodeMillis` timeout and failed.
Looking at the Swarm client logs, I saw that Swarm had successfully called `SwarmClient#createSwarmAgent` against the controller and had proceeded to delegate to Remoting. Remoting was then logging
```
2021-04-28 14:53:26 WARNING org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver isPortVisible Connection refused (Connection refused)
2021-04-28 14:53:26 SEVERE …
```
> Allow JNLP agent endpoint resolution exceptions to be non-fatal for Swarm

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
I'm working on the ticket below.
[[JENKINS-40700] Display communication  protocol in agent logs](https://issues.jenkins.io/browse/JENKINS-40700)
And this is the continuation of #450.
#450 enables the current Engine to hold the name of the using communication protocol such as `JNLP4-connect`.
This PR enables Launcher to hold communication protocol name such as `TCP (remote: client)` or `Standard in/out`
I submitted the PR that uses this feature on the controller side to [jenkinsci / jenkins](https://github.com/jenkinsci/jenkins).
link: jenkinsci/jenkins#5459
> [JENKINS-40700] Enable Launcher to hold the communication protocol.

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/jnlp/Main.java
Add the -websocketHeader flag to add additional custom headers to the connection request.
These additional headers are then used when connecting to jenkins via websockets.
Use-case: You have a reverse proxy in front of jenkins that requires custom headers to authenticate/route correctly.
Supercedes #455
> Allow setting of custom websocket headers

- src/main/java/hudson/remoting/Engine.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
I noticed in CloudBees CI trying to launch a shared agent in WebSocket mode from the Java Web Start button an error indicating that the equivalent of https://github.com/jenkinsci/slave-installer-module/blob/8ab32a0616d147adef0d27fb51a359796e069eeb/src/main/java/org/jenkinsci/modules/slave_installer/impl/InstallerGui.java#L78 was throwing an NPE, despite the Jenkins root URL being configured. I could not reproduce a similar stack trace using an OSS agent connection, though the installer menu was not created either, so maybe the exception was just swallowed somewhere, or printed to the agent log which I forgot to check. Anyway, it seems clear from code that this `getHudsonUrl` method would have worked in TCP but not WebSocket mode.
Also cleaning up a trailing slash check introduced in #391. …
> Define `hudsonUrl` in WebSocket mode to fix agent installers

- src/main/java/hudson/remoting/Request.java
Fixes log messages which failed to convey useful information. Also see #274.
> Logging should be of `Request` which has a `toString`, not some anonymous `Runnable`

- src/main/java/hudson/remoting/Launcher.java
https://issues.jenkins.io/browse/JENKINS-64831
> [JENKINS-64831] Deprecate the `-cp` option to `Launcher`

- src/main/java/hudson/remoting/jnlp/Main.java
Running an agent on Java 17:
```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by hudson.remoting.jnlp.Main (file:/Users/timja/Downloads/agent.jar)
WARNING: Please consider reporting this to the maintainers of hudson.remoting.jnlp.Main
WARNING: System::setSecurityManager will be removed in a future release
```
> Remove setting of null security manager

- src/main/java/org/jenkinsci/remoting/protocol/ProtocolLayer.java
The documentation states:
> A handy constant until Java 7 compatibility can be assumed.
Java 7 compatiblity can now be assumed.
[`usage-in-plugins`](https://ci.jenkins.io/job/Infra/job/usage-in-plugins/job/master/) says this is unused.
> Remove unused `ProtocolLayer#UTF_8` field

- pom.xml
**Untested** but may fix [JENKINS-61212](https://issues.jenkins.io/browse/JENKINS-61212) by picking up https://github.com/eclipse-ee4j/tyrus/pull/707. Also see https://github.com/jenkinsci/jenkins/pull/5716 for the CLI.
> [JENKINS-61212] Update Tyrus (WebSocket client) to 1.18

- pom.xml
- src/main/java/hudson/remoting/Callable.java
- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelBuilder.java
- src/main/java/hudson/remoting/PingThread.java
- src/main/java/hudson/remoting/RequiredRoleCheckerWrapper.java
- src/main/java/org/jenkinsci/remoting/RoleChecker.java
Context:
https://www.jenkins.io/doc/upgrade-guide/2.303/#SECURITY-2458
https://www.jenkins.io/doc/developer/security/remoting-callables/
Probably debatable whether we want to keep the new behavior to allow `RoleChecker#check(RoleSensitive)`; probably makes sense to amend this and just allow all remoting callables to ignore the role check (not just some). For now, this needs merging so that the released change is on `master` though.
> Integrate SECURITY-2458 changes

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/ChannelBuilder.java
- src/main/java/hudson/remoting/InternalCallable.java
- src/main/java/hudson/remoting/PingThread.java
- src/main/java/hudson/remoting/RemoteInvocationHandler.java
- src/main/java/org/jenkinsci/remoting/RoleChecker.java
This removes the need to support `RoleChecker#check(RoleSensitive)`
Downstream PR: https://github.com/jenkinsci/jenkins/pull/5901
Corresponding docs update: https://github.com/jenkins-infra/jenkins.io/pull/4707
----
During development of the [SECURITY-2458 security hardening](https://www.jenkins.io/doc/book/security/controller-isolation/required-role-check/), we noticed some `Callable`s defined in remoting would be rejected; but they couldn't perform a real role check, because application-level roles aren't known to remoting.
Additionally, I thought it might be useful to allow calling `RoleChecker#check(RoleSensitive, Role...)` without any `Role`, to indicate that a `Callable` doesn't wish to limit where it can execute. Unfortunately this didn't work for `RPCRequest` because it would …
> Allow all remoting callables to bypass role check

- src/main/java/hudson/remoting/jnlp/Main.java
https://issues.jenkins.io/browse/JENKINS-67000
Reverts #481 pending a more nuanced fix.
> [JENKINS-67000] Restore setting of null security manager

- src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
- src/main/java/org/jenkinsci/remoting/protocol/FilterLayer.java
- src/main/java/org/jenkinsci/remoting/protocol/NetworkLayer.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/AckFilterLayer.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/BIONetworkLayer.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayer.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.java
- src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java
- src/main/java/org/jenkinsci/remoting/util/ByteBufferQueueInputStream.java
- src/main/java/org/jenkinsci/remoting/util/ByteBufferUtils.java
- src/main/java/org/jenkinsci/remoting/util/DirectByteBufferPool.java
See jenkinsci/stapler#321. Noticed when pulling in jenkinsci/pom#226 in #508, where I got the following errors:
<details>
<summary>Animal Sniffer errors</summary>
<pre>
[ERROR] src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java:143: Undefined reference: java.nio.ByteBuffer java.nio.ByteBuffer.clear()
[ERROR] src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java:169: Undefined reference: java.nio.ByteBuffer java.nio.ByteBuffer.limit(int)
[ERROR] src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java:171: Undefined reference: java.nio.ByteBuffer java.nio.ByteBuffer.limit(int)
[ERROR] src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java:301: Undefined reference: java.nio.ByteBuffer java.nio.ByteBuffer.clear()
[ERROR] …
> Fix `ByteBuffer`-related Animal Sniffer errors

- src/main/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.java
**Background**
I've found increased CPU load at my Jenkins instance.
The root cause of CPU load was a thread that is stuck in an infinite loop in SSLEngineFilterLayer.java
The remote agent was already terminated by kubernetes-plugin and the SSL connection is closed, but the thread is still working because can't exit from the while loop.
**Solution**
Set _done_ flag in case of receiving `SSLEngineResult.Status.CLOSED` from `sslEngine.unwrap(tempBuffer, appBuffer)`.
This change is allowed to return execution flow to `NIONetworkLayer.ready()` where the thread will handle ClosedChannelException.
**Libraries versions**
Jenkins core - 2.319.3
kubernetes - 1.31.3
remoting - 4.11.2
> JENKINS-67928 Prevent infinite loop in case of closed SSL connection

- src/main/java/hudson/remoting/Engine.java
Extracts the logic from https://github.com/jenkinsci/remoting/pull/295 which wasn't re-used in the websocket protocol
See https://issues.jenkins.io/browse/JENKINS-66446
To reproduce:
1. Use Java 11 on the agent
2. Create a Permanent agent with websocket protocol enabled
3. Restart the controller
4. It should fail to reconnect the agent with a `NoClassDefFoundError: jenkins/slaves/restarter/JnlpSlaveRestarterInstaller`
5. Repeat steps with this patch, reconnects just fine
> JENKINS-66446 Agent reconnects on Java 11 and websocket

- Jenkinsfile
- pom.xml
- src/main/java/hudson/remoting/CommandTransport.java
Update the build/test matrix to include recent versions of Java, as is being done in other core components.
> Add Java 11 and 17 to build/test matrix

- pom.xml
Building this plugin on a system with large UID / GID fails due to
```
user id '<< Long UID >>' is too big ( > 2097151 )
```
This is a known issue of assembly-plugin, using POSIX `tarLongFileMode` solves it.
- https://issues.apache.org/jira/browse/MASSEMBLY-728
- https://stackoverflow.com/questions/30246705/mvn-failure-on-build
- https://stackoverflow.com/questions/33819438/maven-assembly-plugin-group-id-1377585961-is-too-big-error
---------------------------------------
> Set tarLongFileMode to enable building on systems with large UID / GID

- src/main/java/org/jenkinsci/remoting/util/AnonymousClassWarnings.java
Split from #505.
Anonymous class check is done async and is not a critical process, so it shouldn't use more than one thread at a time.
> [JENKINS-65873] Throttle anonymous class warnings to a single thread

- src/main/java/hudson/remoting/JarCacheSupport.java
- src/main/java/hudson/remoting/UserRequest.java
Irritated while running https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/195:
```
… hudson.remoting.JarCacheSupport$DownloadRunnable run
WARNING: Failed to resolve a jar 96455c4416b1dfc9256f9617336c0f7d
java.io.IOException: Failed to write to …/remoting/jarCache/96/455C4416B1DFC9256F9617336C0F7D.jar
at hudson.remoting.FileSystemJarCache.retrieve(FileSystemJarCache.java:148)
at hudson.remoting.JarCacheSupport$DownloadRunnable.run(JarCacheSupport.java:113)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Backing channel 'JNLP4-connect …
```
> Suppress some uninteresting stack traces when channel is closed

- src/main/java/hudson/remoting/Engine.java
[JENKINS-68542](https://issues.jenkins.io/browse/JENKINS-68542)
Cherry-picked from cc32c3b (#537)
Remoting 4.13 is the version pinned on Jenkins LTS [2.332](https://github.com/jenkinsci/jenkins/blob/stable-2.332/pom.xml#L93) and [2.346](https://github.com/jenkinsci/jenkins/blob/stable-2.346/pom.xml#L93)
> [JENKINS-68542] [WebSocket] Capture cookie returned by server and reuse for reconnection attempts

- src/main/java/hudson/remoting/Engine.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpConnectionState.java
Follows-up #537, needed for https://github.com/jenkinsci/jenkins/pull/6576
The previous value was not a valid HTTP header name and could get
filtered by reverse proxies such as nginx, causing the previous fix not to work when using such setup.
> [JENKINS-68542] Rename the header used for connection cookie

- pom.xml
In https://github.com/jenkinsci/jenkins/pull/6658 I noticed that `remoting.jar` was shipping a bunch of Java and HTML files in `OSGI-OPT` that are also contained in `args4j-2.33.jar`, which was tripping up `ClassPathTest` in Jenkins core. It is probably a bug that these files are included in `args4j-2.33.jar` in the first place, but since we do not have direct control over that library and [my last pull request from July 4, 2021](https://github.com/kohsuke/args4j/pull/182) remains unacknowledged 11 months later, the least we can do is not propagate this error in `remoting.jar`. This PR filters out these unneeded files. To test this PR, I successfully ran `ClassPathTest` from https://github.com/jenkinsci/jenkins/pull/6658 with these exclusions removed.
> Remove args4j `OSGI-OPT` files

- src/test/java/hudson/remoting/PrefetchingTest.java
This pull request fixes either 1.) Temporary Directory Hijacking Vulnerability, or 2.) Temporary Directory Information Disclosure Vulnerability, which existed in this project.
The system temporary directory is shared between all users on most unix-like systems (not MacOS, or Windows). Thus, code interacting with the system temporary directory must be careful about file interactions in this directory, and must ensure that the correct file permissions are set.
This PR was generated because the following chain of calls was detected in this repository in a way that leaves this project vulnerable.
`File.createTempFile(..)` -> `file.delete()` -> either `file.mkdir()` or `file.mkdirs()`.
This vulnerability can have one of two impacts depending upon which vulnerability it is.
1. Temporary …
> [SECURITY] Fix Temporary Directory Information Disclosure Vulnerability in test

- pom.xml
Like https://github.com/jenkinsci/bouncycastle-api-plugin/pull/91 but for Remoting tests. Per the documentation:
> **Packaging Change (users of 1.70 or earlier):** BC 1.71 changed the `jdk15on` jars to `jdk18on` so the base has now moved to Java 8. For earlier JVMs, or containers/applications that cannot cope with multi-release jars, you should now use the `jdk15to18` jars.
Jenkins core has supported multi-release JARs since https://github.com/jenkinsci/jenkins/pull/5635, so this should be no problem.
> Upgrade Bouncy Castle from 1.70 to 1.71

- pom.xml
These have been in the parent POM since https://github.com/jenkinsci/pom/pull/257 which was released in 1.76.
> Remove redundant `project.reporting.outputEncoding` and `project.build.outputEncoding` properties

- pom.xml
This has been in the parent POM since https://github.com/jenkinsci/pom/pull/273 which was released in 1.79.
> Remove redundant `all-tests` profile

- pom.xml
This version is already defined in the parent POM.
> Remove redundant `maven-assembly-plugin` version

- src/main/java/hudson/remoting/ClassLoaderHolder.java
- src/main/java/hudson/remoting/ClassicCommandTransport.java
- src/main/java/hudson/remoting/RequiredRoleCheckerWrapper.java
- src/test/java/hudson/remoting/ChunkedInputStreamTest.java
Added missing `@NonNull` and `@CheckForNull` annotations on overrides
> Added missing `@NonNull` and `@CheckForNull` annotations

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Propose a quick improvement to display the host that is actually used to test that the JNLP port is unreachable. That message is often misleading because it is showing the Jenkins URL.
> Improve JNLP Port Unreachable error message with host value

- src/main/java/hudson/remoting/Engine.java
More information in [JENKINS-69890](https://issues.jenkins.io/browse/JENKINS-69890)
> [JENKINS-69890] Prevent deadlock on websocket agents

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
While reading this code recently I found the logic unnecessarily complex. This PR makes the logic 38 lines shorter without any change in functionality. I tested this change against Jenkins core with `mvn clean verify -Dtest=hudson.slaves.ChannelPingerTest,hudson.slaves.JNLPLauncherTest,hudson.slaves.PingThreadTest,hudson.slaves.SlaveComputerTest,jenkins.agents.WebSocketAgentsTest,jenkins.security.AgentToControllerSecurityTest,jenkins.security.CustomClassFilterTest,jenkins.slaves.OldRemotingAgentTest,jenkins.slaves.RemotingVersionInfoTest,jenkins.slaves.UnsupportedRemotingAgentEscapeHatchTest,jenkins.slaves.UnsupportedRemotingAgentTest`.
> Simplify header parsing logic

- src/main/java/hudson/remoting/Engine.java
More information in [JENKINS-70105](https://issues.jenkins.io/browse/JENKINS-70105).
This is aligned with the existent inbound tcp agent re-connect logic, which is waiting for 10 seconds before each re-try.
The original logic was waiting 10 seconds only if the controller was not responding.
> [JENKINS-70105] Slow down websocket re-connect

- src/spotbugs/excludesFilter.xml
Recent versions of SpotBugs have gotten a lot better at running on Java 11/17, and a lot of false positives that we had to exclude previously are no longer relevant. This PR deletes any such unnecessary exclusions. To test this, I ran `mvn clean verify -DskipTests` on both Java 11 and 17.
> Remove unnecessary SpotBugs exclusions

- src/test/java/hudson/remoting/PipeTest.java
https://github.com/jenkinsci/remoting/pull/593#discussion_r994877261 superseded by https://github.com/jenkinsci/remoting/pull/593/commits/f918dff7060eb7abfa53eced7bbbb4ca0b7bf072
> Remove 2s timeout in `PipeTest.testReaderCloseWhileWriterIsStillWriting`

- pom.xml
Fixes the following Maven Shade Plugin warning
```
[WARNING] args4j-2.33.jar, constant-pool-scanner-1.2.jar, remoting-999999-SNAPSHOT.jar, tyrus-standalone-client-jdk-2.1.2.jar define 1 overlapping resource: 
[WARNING]   - META-INF/MANIFEST.MF
```
by excluding the `MANIFEST.MF` for any dependencies, leaving only our own. Tested by ensuring that the warning is now gone and that the `MANIFEST.MF` in the delivered Remoting JAR is the same before and after this PR.
> Fix Maven Shade Plugin warnings

- src/test/java/hudson/remoting/PipeTest.java
#612, https://github.com/jenkinsci/remoting/pull/593#discussion_r994877261
> `PipeTest.testReaderCloseWhileWriterIsStillWriting` is flaky; disabling

- src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
- src/main/java/hudson/remoting/ChunkHeader.java
- src/main/java/hudson/remoting/Engine.java
- src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
- src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
A user reported a WebSocket agent hanging indefinitely after a reload of nginx configuration
```
"pool-1-thread-… for … id=… / waiting for … id=…" #… daemon prio=5 os_prio=0 cpu=89.18ms elapsed=300.35s tid=… nid=… waiting on condition  […]
java.lang.Thread.State: WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@11.0.17/Native Method)
- parking to wait for  <…> (a java.util.concurrent.CountDownLatch$Sync)
at java.util.concurrent.locks.LockSupport.park(java.base@11.0.17/LockSupport.java:194)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.17/AbstractQueuedSynchronizer.java:885)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.17/AbstractQueuedSynchronizer.java:1039)
at …
```
> [JENKINS-70531] Apply timeout on WebSocket write operations (and simplify `AbstractByteBufferCommandTransport`)

- src/test/java/hudson/remoting/DefaultClassFilterTest.java
- src/test/java/hudson/remoting/LauncherTest.java
- src/test/java/org/jenkinsci/remoting/engine/HostPortTest.java
- src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
With https://github.com/jenkinsci/remoting/pull/639 in mind, we can use native `hamcrest` imports, independent of the deprecated -core module.
> Adapt hamcrest methods

- src/test/java/hudson/remoting/DefaultClassFilterTest.java
- src/test/java/hudson/remoting/LauncherTest.java
- src/test/java/hudson/remoting/PrefetchingTest.java
With https://github.com/jenkinsci/remoting/pull/640 in mind, we can make use of the non-deprecated methods of the -core module here too.
> Hamcrest internal cleanup

- src/test/java/hudson/remoting/ChannelTest.java
- src/test/java/hudson/remoting/ClassRemoting2Test.java
- src/test/java/hudson/remoting/ClassRemotingTest.java
- src/test/java/hudson/remoting/PrefetchTest.java
- src/test/java/hudson/remoting/PrefetchingTest.java
- src/test/java/hudson/remoting/RegExpBenchmark.java
- src/test/java/org/jenkinsci/remoting/protocol/IOHubTest.java
- src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackImplTest.java
Some failures observed in CI, but mainly just running
```bash
mvn test -DforkCount=.45C
```
(about five concurrent tests on my machine) over and over. Surprisingly hard to get a clean run; #142 masks poor tests and we do not yet have the infrastructure to track flakes (maybe Launchable could).
> Managing test flakes

- src/main/java/hudson/remoting/ProxyException.java
- src/test/java/hudson/remoting/ProxyExceptionTest.java
`ProxyException` currently throws a `StackOverflowError` if passed a `Throwable` which contains cycles in its graph of causes and suppressed throwables. This PR fixes that issue by breaking cycles when proxying throwables.
In particular, this is relevant for Pipeline, which uses `ProxyException` to create serializable versions of errors in some cases. See [ErrorAction](https://github.com/jenkinsci/workflow-api-plugin/blob/646def1087f9b2730a3b4f9e575c56e0fc13b492/src/main/java/org/jenkinsci/plugins/workflow/actions/ErrorAction.java) and https://github.com/jenkinsci/workflow-api-plugin/pull/286.
Automated tests added.
> Prevent ProxyException from throwing StackOverflowError on cyclic errors by breaking cycles

- src/main/java/hudson/remoting/Channel.java
Introduced in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/231, already copied to a CloudBees CI plugin, and now in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/323 probably needed also in both `durable-task` and `workflow-api`, which have no common dependencies. In general it is pretty common to want to log exceptions of this type at a low level. Makes more sense to define it in Remoting where it can be easily reused.
> Introduce convenience method `Channel.isClosedChannelException`

- src/main/java/hudson/remoting/TeeOutputStream.java
- src/test/java/hudson/remoting/TeeOutputStreamTest.java
See [JENKINS-38520](https://issues.jenkins.io/browse/JENKINS-38520) and [JENKINS-71856](https://issues.jenkins.io/browse/JENKINS-71856). Adds a new test from https://github.com/apache/commons-io/blob/dec88cac5b77a98daa58f7e876d4440dfeb42aea/src/main/java/org/apache/commons/io/output/TeeOutputStream.java that demonstrates the problem. Fixes the problem by backporting the latest changes to `TeeOutputStream` from https://github.com/apache/commons-io/blob/dec88cac5b77a98daa58f7e876d4440dfeb42aea/src/main/java/org/apache/commons/io/output/TeeOutputStream.java.
Ran the unit test locally.
```[tasklist]
```
> [JENKINS-38520] Every message in agent log appears twice with the `-agentLog` option

- src/main/java/org/jenkinsci/remoting/org/apache/commons/net/util/SubnetUtils.java
- src/test/java/org/jenkinsci/remoting/org/apache/commons/net/util/SubnetUtilsTest.java
In #312 with had inlined a copy of `SubnetUtils` from Commons Net 3.6 and proceeded to never upgrade it. This PR upgrades that class and its test to the latest code from version 3.9.0
Ran the unit test locally.
> Upgrade Commons Net from 3.6 to 3.9.0

- src/test/java/hudson/remoting/ChannelRunner.java
- src/test/java/hudson/remoting/DiagnosedStreamCorruptionExceptionTest.java
- src/test/java/hudson/remoting/PipeTest.java
- src/test/java/hudson/remoting/PrefetchingTest.java
- src/test/java/hudson/remoting/throughput/DumbReceiver.java
- src/test/java/hudson/remoting/throughput/Sender.java
use `NullOutputStream.INSTANCE` instead of deprecated `NullOutputStream.NULL_OUTPUT_STREAM` (in Tests) and removed two unused imports
Ran all unit tests
```[tasklist]
```
> Test with `NullOutputStream.INSTANCE` instead of deprecated `NULL_OUTPUT_STREAM`

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
JENKINS-65368: isPortVisible did not take into account any proxy, prohibiting the agent from connecting through a proxy.
Because of this, the agent would think the jnlp port is closed (when the port is exclusively accesible through the proxy) and will fail the connect.
- n/a Link to relevant pull requests, esp. upstream and downstream changes
- :( Ensure you have provided tests - that demonstrates feature works or fixes the issue. -> Wasn't able to come up with a test, added logging as proof.
Additional context: I've privately patched these two lines in my organization on many agent releases between 3.36 and the current, so i figured i should take the effort of bringing this fix to the release. Not sure why the corresponding issue was closed. Hope this PR finds you well.
> JENKINS-65368: isPortVisible did not take into account any proxy

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
See [JENKINS-72163](https://issues.jenkins.io/browse/JENKINS-72163).
I talked to a user running Kubernetes agents in a cluster where the controller was not immediately reachable over the network after spinning up the agent. Rather, it took 30 seconds or so for the controller to become reachable over the network. While admitting this networking setup was not ideal, the user expected Remoting to be resilient to this scenario, but it was not. Rather, Remoting printed the following exception and then terminated with a non-zero exit code, never trying again:
```java
java.io.IOException: Failed to connect to http://example.com/tcpSlaveAgentListener/: Connection refused
at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:216)
at …
```
> [JENKINS-72163] Retry on initial connection failure occurs in one entrypoint but not the other

- src/main/java/org/jenkinsci/remoting/protocol/impl/PermanentConnectionRefusalException.java
From this class’ Javadoc
> no further connection attempts should be made
you would infer that throwing this error would produce different behavior compared to `ConnectionRefusalException`: rather than temporarily refusing a connection but letting the agent retry, the agent would immediately give up and exit. Yet it does not appear to actually do that, and from what I can tell going back to its introduction in #92 it never did.
First of all, no code actually uses this exception type currently. https://github.com/jenkinsci/remoting/blob/3b293d50275b7da9dffdd5354d2a744fbbf7c072/src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayer.java#L378-L379 is merely wrapping an exception already caught. https://github.com/jenkinsci/remoting/blob/3b293d50275b7da9dffdd5354d2a744f …
> Deprecating `PermanentConnectionRefusalException`

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Otherwise it is not necessarily clear from log messages where the agent was _trying_ to connect.
> Better logging of controller URL from `JnlpAgentEndpointResolver`

- src/main/java/hudson/remoting/Engine.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointConfigurator.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
While testing #677 I noticed that proxy authentication was broken even on trunk, no matter which combination of entrypoints and parameters I tried. If we advertise a `-proxyCredentials` flag, then it should at least work. This PR gets the flag to work as advertised.
Set up a Squid forward proxy that required authentication, then ran:
`java -Djdk.http.auth.tunneling.disabledSchemes= -Dhttp.proxyHost=${IP_ADDRESS} -Dhttp.proxyPort=3128 -jar target/remoting-999999-SNAPSHOT.jar -url ${JENKINS_URL} -secret ${SECRET} -name test -proxyCredentials ${USERNAME}:${PASSWORD}`
Before this PR it either failed either in the `isPortVisible` method or when trying to actually establish the tunnel. Now it works in both places.
> Fix proxy authentication

- src/main/java/hudson/remoting/Launcher.java
https://github.com/jenkinsci/remoting/pull/677#discussion_r1368634576 by code inspection; have not yet checked how to test in Kubernetes (would require building an agent image from source).
> Fixing `-direct`

- src/main/java/hudson/remoting/Launcher.java
When migrating `@Option` from the setter to the field (and deprecating the setter) I neglected to also make the field `public` (like all other `@Option` fields) as I discovered when trying to migrate Swarm away from the deprecated usage.
> Increase visibility of field

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
I couldn't see a good reason to support these in one transport but not the other, given that it is just a matter of plumbing through the relevant `SSLContext` to the HTTP layer.
Set up a WebSocket agent against my controller with a self-signed HTTPS certificate. Verified the connection failed before this PR and passed after this PR when adding `-noCertificateCheck`. I also tested that I could connect with HTTPS and `-noCertificateCheck` _without_ WebSocket. I did not test `-cert` because I don't actually have a valid certificate for my local testing environment. But this code is common code, so if it's plumbed through correctly in one case it should be plumbed through correctly in the other as well.
> Support `-cert` and `-noCertificateCheck` in WebSocket mode

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
This component supports the `http.proxyHost` system property (or `proxy_host` environment variable) for configuring a proxy server, but it is not honored in WebSocket mode. By plumbing this through to Tyrus we can get Tyrus to respect the proxy settings the same way non-WebSocket mode does. Similarly we can plumb through the value of `-proxyCredentials` to Tyrus if the user needs to pass in a `Proxy-Authorization` header (like we do in non-WebSocket mode). We do this only for HTTP to match the non-WebSocket mode.
Set up a Squid proxy that required authentication and verified that I could connect through it using:
```
java -Dhttp.proxyHost=${HOSTNAME} -Dhttp.proxyPort=3128 -jar target/remoting-999999-SNAPSHOT.jar -url ${JENKINS_URL} -secret ${SECRET} -name test -webSocket -proxyCredentials …
```
> Proxy support for WebSocket

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Found a minor issue when trying to refactor Swarm to take advantage of these recent changes: Swarm directly calls `Launcher#parseJnlpArguments` to get the secret from the server (and can't easily be changed to stop doing this), and that currently means that the initialization logic from `Launcher#run` doesn't get run, so things like `-noCertificateCheck` are working only by accident in that their initialization is done lazily rather than eagerly. This PR fixes that problem and makes the code more easy to understand by putting all initialization logic in one place and ensuring that all public entrypoints invoke it exactly once, and eagerly at the beginning of program launch.
We also took the various initialization paradigms and made them consistent: eager rather than lazy, using the same …
> Move initialization to common method for Swarm

- src/main/java/hudson/remoting/Request.java
Noticed in a heap dump that there were several `Channel`s sticking around after the associated builds had completed, and found that they were referenced in a log ring buffer
```
this     - value: hudson.remoting.Channel #1
<- channel     - class: hudson.remoting.RemoteClassLoader$ClassLoaderProxy, value: hudson.remoting.Channel #1
<- classLoaderProxy     - class: hudson.remoting.UserRequest, value: hudson.remoting.RemoteClassLoader$ClassLoaderProxy #1
<- [0]     - class: java.lang.Object[], value: hudson.remoting.UserRequest #1
<- parameters     - class: java.util.logging.LogRecord, value: java.lang.Object[] #97789
<- [177]     - class: java.util.logging.LogRecord[], value: java.util.logging.LogRecord #32
<- records     - class: hudson.WebAppMain$1, value: java.util.logging.LogRecord[] #1 …
```
> Avoid capturing `Request` in `LogRecord` parameters

- src/main/java/hudson/remoting/Launcher.java
As of jenkinsci/jenkins#6723 this is no longer used and would not work on Java 9+ anyway, which we have been requiring for quite some time now.
CI build
> Remove deprecated `-cp` argument

- src/main/java/hudson/remoting/Launcher.java
I searched for usages in `jenkinsci`, `jenkins-infra`, and `cloudbees` and found no usages of this still left. The only usage of this was in Swarm Client, but I refactored and released a new version yesterday that no longer uses this deprecated method.
CI build
> Remove deprecated `Launcher#setNoCertificateCheck`

- src/main/java/hudson/remoting/jnlp/Main.java
Now that consumers have been migrated to the new entrypoint, get more aggressive about logging warnings when using the old one.
Ran both the old and new entrypoints and verified the old one printed a deprecation warning.
> Log deprecation warning when using deprecated `hudson.remoting.jnlp.Main` entrypoint

- src/main/java/hudson/remoting/Launcher.java
Now that I have migrated common usages away from these deprecated arguments, ensure that a warning is printed if a user is still invoking Remoting with a deprecated argument. I haven't yet added a warning for `-jnlpUrl` because I want to wait for https://github.com/jenkinsci/jenkins/pull/8639 to ship in a few weekly releases first. The `-tcp` and `-connectTo` arguments weren't deprecated at the command-line argument level but their implementations were marked with `@Deprecated`, so I am deprecating the command-line arguments too for consistency. I could find no uses besides the WMI Windows Agents plugin tests, and that plugin is itself already deprecated.
Invoked the various arguments at the command-line and verified that a deprecation warning was printed.
> Print deprecation warning when deprecated arguments are used

- src/main/java/hudson/remoting/Launcher.java
Be consistent with other code in this class that directly throws `IOException` at the top level rather than wrapping it in some other exception type.
CI build should be sufficient.
> Directly throw `IOException`

- src/main/java/hudson/remoting/Launcher.java
Now that https://github.com/jenkinsci/jenkins/pull/8639 and https://github.com/jenkinsci/jenkins-test-harness/pull/670 have been shipping for a bit, time to deprecate this legacy usage mode.
Verified that I could connect to the controller with the new calling convention without any warnings and that the warning was printed when using the old calling convention.
> Print deprecation warning when using `-jnlpUrl`

- pom.xml
- src/spotbugs/excludesFilter.xml
Prep for
* https://github.com/jenkinsci/pom/pull/510
Part of the checklist in:
* https://github.com/jenkinsci/jenkins/pull/8803
Needs to be merged on or before the update of the parent pom that updates to use spotbugs 4.8.2.
Confirmed that tests pass for me locally.
> Use spotbugs 4.8.2 with more exclusions

- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/jnlp/Main.java
This method was only ever public for use by Swarm, and as of https://github.com/jenkinsci/swarm-plugin/pull/606 Swarm is not calling it anymore.
Verified in a code search in `jenkinsci` and `cloudbees` that nothing is invoking `parseJnlpArguments` directly.
> Reduce visibility of `parseJnlpArguments`

- src/main/java/hudson/remoting/JarCacheSupport.java
While reading this code recently, I found some complicated logic to deal with a risk of multiple downloads of the same JAR getting scheduled, leading to special code to handle this race condition whose correctness is being challenged in https://github.com/jenkinsci/remoting/pull/709. This complicated logic is not necessary if one instead uses `ConcurrentHashMap#computeIfAbsent`, whose [Javadoc states](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent(K,java.util.function.Function)):
> The entire method invocation is performed atomically, so the function is applied at most once per key.
Due to these exactly once semantics, we don't have to worry about a race condition, so we can simplify the logic considerably, deleting …
> Use `ConcurrentHashMap#computeIfAbsent` in `JarCacheSupport`

- src/main/java/hudson/remoting/JarCache.java
- src/main/java/hudson/remoting/JarCacheSupport.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/hudson/remoting/ResourceImageBoth.java
- src/main/java/hudson/remoting/ResourceImageDirect.java
- src/main/java/hudson/remoting/ResourceImageInJar.java
- src/main/java/hudson/remoting/ResourceImageRef.java
When reading this code recently, I noticed we were using some custom classes like `AsyncFutureImpl` and `FutureAdapter` which now have equivalents in the Java Platform. I thought the code was easier to read when using the standard classes rather than our custom ones.
This is a tiny public API change for `hudson.remoting.JarCache` and a handful of package-private internal classes, but I searched in `jenkinsci` and `cloudbees` and found no consumers outside of Remoting itself, so this change seems safe from an API compatibility point of view.
I stepped through the code in the debugger before and after and found one minor change: when downloading a JAR for the first time, the chained future to read the file into memory from `ResourceImageInJar` runs immediately as part of the …
> Use `CompletableFuture` in `JarCache`

- src/main/java/hudson/remoting/JarCacheSupport.java
An implicit invariant in `JarCacheSupport` is that `DownloadRunnable` is only ever processing the promise that is currently recorded in the `inprogress` map, an invariant which can be proved by reading the code and studying the cases that arise. This PR hardens the code by enforcing this invariant programmatically and throwing an `IllegalStateException` if the invariant is violated, which would only be the case if a future PR introduced a programming error.
I ran a job on an inbound agent to check out a repository with JGit and verified that the new assertion was never thrown (as expected).
> Harden `JarCacheSupport`

- pom.xml
Removes cd91eea5dc25cee827a502d0b40423312f5bb11 workaround that was added in https://github.com/jenkinsci/remoting/pull/708
https://github.com/jenkinsci/pom/pull/510 is the pull request to the parent pom.  It was released in parent pom 1.109.
Confirmed that spotbugs output is still silent after the change.
```[tasklist]
```
> Rely on parent pom spotbugs configuration

- src/main/java/hudson/remoting/Checksum.java
- src/test/java/hudson/remoting/DiagnosedStreamCorruptionExceptionTest.java
- src/test/java/hudson/remoting/PipeTest.java
- src/test/java/hudson/remoting/throughput/DumbReceiver.java
- src/test/java/hudson/remoting/throughput/Sender.java
- src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
While reading this code recently, I found a few dozen lines of code that could be deleted by using Java 9+ functionality instead. This PR only touches tests with the exception of the change to `Checksum.java` which can be trivially verified.
> Use Java 11 methods where possible

- src/test/java/hudson/remoting/ForkRunner.java
The classpath on windows was pure fantasy and worked by fluke only if java and all the code and dependencies where on the same drive.
if any code was on a different drive the classpath was mangled which leads to tests failing.
e.g.  the classpath would end up being something like
```
D;\source\github\jenkins\remoting\target\test-classes;D;\source\github\jenkins\remoting\target\classes;C;\Users\jnord\.m2\repository\args4j\args4j\2.33\args4j-2.33.jar;C;\Users\jnord\.m2\repository\org\glassfish\tyrus\bundles\tyrus-standalone-client-jdk\2.1.5\tyrus-standalone-client-jdk-2.1.5.jar;C;\Users\jnord\.m2\repository\org\jenkins-ci\constant-pool-scanner\1.2\constant-pool-scanner-1.2.jar;C;\Users\jnord\.m2\repository\com\github\spotbugs\spotbugs-annotations\4.8.5\spotbugs-annotations-4.8.5.jar;C;\Users …
```
> Fix incorrect classpath leading to broken tests

- .mvn/jvm.config
- pom.xml
- src/test/java/hudson/remoting/ForkRunner.java
whilst running tests I experienced some random memory issues.
As there was no attempt at running maven / surefire or even the JVM spawned inside a test with amy memory limits I added some.
The memory chosen may or may not be optimal, no attempt has been made to optimize the values.  they have mostly be taken from other places that are known to be reasonable.
`mvn deploy`
```[tasklist]
```
> introduce memory limits (in tests)

- src/main/java/hudson/remoting/DumbClassLoaderBridge.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
Created a version of Jenkins with a local build of this, attached a debugger to an `ssh-slaves` agent and put a breakpoint on some code that runs in the agent (from the git-client plugin) to observe classloading.
See https://github.com/jenkinsci/jenkins/pull/9277 
```[tasklist]
```
> Pass through the remote `ClassLoader`’s name

- src/main/java/hudson/remoting/RemoteClassLoader.java
sets the since version https://github.com/jenkinsci/remoting/pull/741/files#r1601332693 to the actual release version.
There is no need for this as the version in the code is higher than the previous release without this method and lower than the version with this method.   But it's wrong and it makes me feel dirty :) 
```[tasklist]
```
> set since to released version

- src/main/java/hudson/remoting/RemoteClassLoader.java
[3244.vf7f977e04755](https://github.com/jenkinsci/remoting/releases/tag/3244.vf7f977e04755) requires the agent to be upgraded in lockstep with Jenkins to avoid remoting errors such as:
```
java.lang.IllegalStateException: Unable to call getName. No matching method found in [interface hudson.remoting.RemoteClassLoader$IClassLoader] for hudson.remoting.RemoteClassLoader$ClassLoaderProxy@2cdf8d8a[jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a]
```
This restores the compatibility by catching the `IllegalStateException` when calling `proxy.getName()` and returning a dummy value
* updated Jenkins core to this version and obseved the `OldRemotingAgentTest` no longer fails.
* connected an agent with this patch to an older jenkins (2.426.3).
** validated it connected
** ran …
> Restore compatibility for older versions

- pom.xml
Amends #748. I think it is still a little too early to start requiring Java 17 here, as Remoting is still used on agents that might be connecting to a Java 11 LTS release. In the absence of a pressing need to use Java 17, seems simpler to wait until at least the end of October to do this.
`mvn clean verify`
> Downgrade to Java 11

- .git-blame-ignore-revs
- pom.xml
- Add `.git-blame.ignore-revs`
- Disable `spotless.check.skip` (forgotten in previous PR)
> Spotless follow-up PR

- pom.xml
Guava versions prior to 32.0.0 have two issues reported:
* [Guava vulnerable to insecure use of temporary directory](https://github.com/jenkinsci/remoting/security/dependabot/4)
* [Information Disclosure in Guava](https://github.com/jenkinsci/remoting/security/dependabot/3)
Neither of those issues is any risk to production because this is a test dependency.  However, since Jenkins core is using Guava 33.3.1-jre, let's upgrade this test dependency to use the same Guava version and resolve the dependabot alerts at the same time.
Confirmed that `mvn clean verify` passes with Java 11 and Java 21 on my Linux computer.
> Test with guava 33.3.1-jre, same as Jenkins core

- src/main/java/hudson/remoting/JarLoaderImpl.java
This is already logged through `org.jenkinsci.remoting.util.LoggingChannelListener#onJar`, however since this logger also logs all packets being read or written, this produces too much noise.
With this change, setting a logger on `hudson.remoting.JarLoaderImpl` with level `FINE` will allow to capture all jars being sent over a channel.
> Log the fact that a jar is being sent over channel

- src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
- src/test/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolverTest.java
I noticed some CloudBees CI tests failing in an IPv6 test environment (ref: BEE-52759) where `InboundAgentRule.start` times out because of e.g. `java.lang.IllegalArgumentException: Malformed escape pair at index 22: http://0:0:0:0:0:0:0:1%lo:43723` launching the agent. I think this is because the agent is being asked to connect to a local (loopback) IP address and its proxy detection code is not written to handle general IPv6 `host`s. ~Not tested in context.~ Fixes the test, it seems.
> Tolerate IPv6 scoped IPs from `JnlpAgentEndpointResolver.getResolvedHttpProxyAddress`

- src/test/java/hudson/remoting/DefaultClassFilterTest.java
**Description**
When executing the test `DefaultClassFilterTest.testDefaultsAreUsedIfOverridesAreGarbage`, the intention is to verify the error message when attempting to create a `ClassFilter` instance with invalid overrides. However, running this test prior to others that rely on the `ClassFilter` class may lead to a `java.lang.NoClassDefFoundError`. This error suggests that the JVM previously failed to load the class from the classpath, and subsequently, it won't attempt to load it again, resulting in the error.
To resolve this issue, it is advisable to initialize the `ClassFilter` successfully before running the specified test. By doing so, the class will be loaded successfully, and subsequent tests can proceed without encountering the `NoClassDefFoundError`. This sequential approach …
> Address `java.lang.NoClassDefFoundError` in `DefaultClassFilterTest` Through Fixed Order-Dependent Test Execution

- src/main/java/hudson/remoting/Engine.java
We have observed cases where the websocket connection would fail temporarily with a handshake error that was not retried and causing the agent to fail.
Also, in CloudBees CI HA, there are some cases when an agent is disconnected on purpose and we expect a reconnect attempt as soon as possible. The default 10 seconds delay appeared too long in that case.
To reconcile this use case with the typical failure scenario, I have implemented exponential backoff for retries (immediate, 1 sec, 3 seconds, 7 seconds, 10 seconds).
* WS: Initial connection
* WS: Applying a rolling restart to the controller. The previous fatal handshake error is now retriable and prints a single log line
> Fix websocket connection retries logic

- src/main/java/hudson/remoting/ClassFilter.java
- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/GCCommand.java
- src/main/java/hudson/remoting/JarLoaderImpl.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/org/jenkinsci/remoting/protocol/ProtocolStack.java
- src/spotbugs/excludesFilter.xml
- Migrates all High and Medium SpotBugs suppressions from XML to Java annotations, where they are easier to manage
- Leaves all Low suppressions in XML
- Removes all unnecessary suppressions
The use of Low rather than Medium dates back to commit 39bc5430d7966e7ab184cb99044ed7510a2adb6b by Kohsuke:
> Couldn't figure out how to add specific checker to the default setting, so I'm activating a whole bunch by setting `threshold=low`, then excluding most of them except the serialization problem
Since these Low threshold violations are frequent and annoying, leaving their suppressions in XML so as not to litter the codebase with unnecessary annotations. Perhaps in the future some better solution can be found to Kohsuke's original problem.
`mvn clean verify`
> Remove unnecessary SpotBugs suppressions

- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/Launcher.java
- src/main/java/hudson/remoting/RemoteClassLoader.java
- src/main/java/org/jenkinsci/remoting/protocol/cert/PublicKeyMatchingX509ExtendedTrustManager.java
These methods are deprecated in the Java Platform, so move to the recommended non-deprecated equivalents.
`mvn clean verify`
> Reduce calls to deprecated Java Platform methods

- src/main/java/hudson/remoting/Channel.java
- src/test/java/hudson/remoting/ChannelTest.java
A Pipeline build with one `InterruptedBuildAction` of `DisableConcurrentBuildsJobProperty.CancelledCause` and another of `ParallelStep.FailFastCause` (originally `AbortException` from `DurableTaskStep.Execution.handleExit`) was observed to be `NOT_BUILT` but its log ended with an endless sequence of
```
…
[Pipeline] End of Pipeline
[2025-04-25T11:31:51.077Z] org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: e947472c-eef7-4c7a-b82f-f58580c9868b
[2025-04-25T11:31:51.078Z] Failed in branch …
[2025-04-25T11:31:51.078Z] org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 82a6526c-292c-47e1-ae90-1ed4fca370c2
[2025-04-25T11:31:51.078Z] org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: e947472c-eef7-4c7a-b82f-f58580c9868b
[2025-04-25T11:31:51.078Z] …
```
> `StackOverflowError` in `isClosedChannelException`

- src/main/java/hudson/remoting/Channel.java
- src/main/java/hudson/remoting/Engine.java
- src/main/java/hudson/remoting/EngineListener.java
- src/main/java/hudson/remoting/EngineListenerSplitter.java
- src/main/java/hudson/remoting/JarCacheSupport.java
- src/main/java/hudson/remoting/Launcher.java
Avoiding `System.exit` when used as an inbound agent (`main(String[])`). The `main` overloads called by `runWithStdinStdout` (or deprecated `runAsTcpServer`) used for outbound agents https://github.com/jenkinsci/remoting/blob/1d80543ebaf27c64e3641d6a67993a13ca9cd7f6/src/main/java/hudson/remoting/Launcher.java#L991-L1065 still `exit`.
Also ensuring that some resources are closed when exiting the (again, inbound) agent loop which were previously leaking threads.
In combination, these fixes make it possible to run multiple (inbound) agents (`Engine`s & `Channel`s) from one JVM, with independent configurations and even class loading after `remoting.jar` itself. Tested in the context of CloudBees CI in high availability mode, where it is unsafe to offer multiple executors from a single agent. …
> Avoid `System.exit` from `Launcher.run`

- src/main/java/hudson/remoting/Engine.java
Minor diagnosability enhancement tangentially related to #805. Otherwise the thread actually doing the work is just called something like `Thread-8`.
> Set `Thread.name` on `Engine`

- src/main/java/hudson/remoting/Engine.java
Compare #675. This is called from `innerRun` which already has its own retry logic.
A TCP agent is used in a Pipeline build as part of an integration test in CloudBees CI which restarts the controller and picks a different host:port after the restart. The shutdown of the original controller naturally causes the agent to disconnect. When it tries to connect again, depending on timing conditions, `JnlpAgentEndpointResolver.resolve` might initially have obtained the old host:port, and then `connectTcp` will try repeatedly to contact it, failing each time. Eventually it will give up and fall back into the main retry loop in `innerRun`, but by that time the resumed build might have given up on the agent reconnecting after a 5m timeout and aborted. At least I do see the 5m timeout, though I do …
> No need to retry inside `connectTcp`
