jenkinsci/remoting

src/main/java/hudson/remoting/AtmostOneThreadExecutor.java

This looked suspect to me.
It may have unintended consequences - but I believe that if it does reveal any issue with this change then the caller is actually broken.
@reviewbybees

A shutdown Executor should not be able to resurect itself

---

src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java

JENKINS-22932

---

src/main/java/hudson/remoting/Channel.java
src/main/java/hudson/remoting/ExportTable.java

See the commit message for more details of this change.
This prevents a hang in channel communication.

When a channel goes down, kill off all Pipes.

---

src/main/java/hudson/remoting/FlightRecorderInputStream.java
src/main/java/hudson/remoting/Launcher.java
src/main/java/hudson/remoting/RemoteInputStream.java
src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java

Java 9 is claiming that as a keyword.

Don't use '_' as an identifier.

---

pom.xml

Guava 14 was released ~2.5 years ago.

Use the latest release of guava.

---

pom.xml

I've also reconfigured the template on the PR builder to publish FindBugs reports.

Update FindBugs to 3.0.2

---

src/main/java/hudson/remoting/Request.java
src/test/java/hudson/remoting/ForkEBCDICRunner.java

callAsync().get() does not return when the channel is closed

---

src/main/java/org/jenkinsci/remoting/nio/FifoBuffer.java

The current implementations do not catch the ChannelClosedException and return -1, instead relying on the implied
behaviour of the JVM to return -1 appropriately. This change fixes the code path so that on newer JVMs the -1
is propagated instead.
Without this change, if you use NioChannelHub to manage client sockets you will get
```
Mar 04, 2016 10:50:56 AM org.jenkinsci.remoting.nio.NioChannelHub run
WARNING: Communication problem
java.nio.channels.ClosedChannelException
at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:256)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:299)
at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:137)
at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:310)
at …
```

The send and receive methods are supposed to return -1 on EOF

---

src/main/java/hudson/remoting/Launcher.java
src/main/java/hudson/remoting/PingThread.java

[JENKINS-35190](https://issues.jenkins-ci.org/browse/JENKINS-35190)
@reviewbybees

[JENKINS-35190] PingThread fixes

---

README.md
docs/configuration.md
src/main/java/hudson/remoting/ClassFilter.java
src/main/java/hudson/remoting/Engine.java
src/main/java/hudson/remoting/FlightRecorderInputStream.java
src/main/java/hudson/remoting/Launcher.java
src/main/java/hudson/remoting/SynchronousCommandTransport.java
src/main/java/hudson/remoting/UserRequest.java
src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol.java

Most likely the settings list is incomplete, I'll add more settings later.

Remoting documentation: README and System properties

---

src/main/java/org/jenkinsci/remoting/engine/JnlpServer3Handshake.java

https://issues.jenkins-ci.org/browse/JENKINS-37140
@reviewbybees

[FIXED JENKINS-37140] Roll the dice again if we are unlucky

---

src/main/java/hudson/remoting/ClassFilter.java

See [JENKINS-37218](https://issues.jenkins-ci.org/browse/JENKINS-37218)

[FIXED JENKINS-37218] Use String.startsWith() for simple patterns

---

src/main/java/hudson/remoting/jnlp/Main.java

https://scan8.coverity.com/reports.htm#v14462/p10499/fileInstanceId=12836384&defectInstanceId=4427348&mergedDefectId=152201
@reviewbybees

[CID-152201] - Fix resource leak in remoting.jnlp.Main

---

src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
src/main/java/org/jenkinsci/remoting/protocol/impl/BIONetworkLayer.java
src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java

See [JENKINS-38344](https://issues.jenkins-ci.org/browse/JENKINS-38344)
@jenkinsci/code-reviewers @reviewbybees (esp @Vlatombe who will have to do some reverting and reapplication to keep internal codebase synced 😉 )

[FIXED JENKINS-38344] Catch uncaught exceptions, log and close connection

---

pom.xml

Just a leftover fix
@reviewbybees

[JENKINS-37565] - Really allow compiling with Java 7

---

Jenkinsfile

This should be able to be replaced at some point in the (hopefully) near future
by some steps in our shared library
(https://github.com/jenkins-infra/pipeline-library) but that's not quite ready
yet

Add a simple Jenkinsfile for building on ci.jenkins.io

---

CHANGELOG.md

It is an attempt to log all incoming changes and to add a disclaimer about the code signing certificate change. The log format is not 100% standard, any suggestions will be appreciated.
@reviewbybees, esp. @stephenc, @rsandell and @jglick since they were reviewing pull requests in this release.

Changelog: Noting changes towards 3.8

---

pom.xml

https://issues.jenkins-ci.org/browse/JENKINS-43623
@reviewbybees @andresrc

[JENKINS-43623] - Change scope of o.g.c.findbugs.annotations to provided

---

docs/logging.md

Follow-up to https://groups.google.com/forum/#!topic/jenkinsci-dev/mgtrxZ0JDok
@reviewbybees

Explicitly say that Logging options are available starting from Remoting 3.8

---

pom.xml
src/main/java/hudson/remoting/Channel.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java

Fix Javadoc and enforce its checks during the build

---

src/main/java/org/jenkinsci/remoting/protocol/IOHub.java

Add IOHub introduction version

---

src/main/java/org/jenkinsci/remoting/engine/Jnlp3ConnectionState.java
src/main/java/org/jenkinsci/remoting/engine/Jnlp4ConnectionState.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
src/main/java/org/jenkinsci/remoting/engine/JnlpClientDatabase.java
src/main/java/org/jenkinsci/remoting/engine/JnlpConnectionState.java
src/main/java/org/jenkinsci/remoting/engine/JnlpConnectionStateListener.java
src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol1Handler.java
src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol2Handler.java
src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol3Handler.java
src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol4Handler.java
src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol4PlainHandler.java
src/main/java/org/jenkinsci/remoting/engine/JnlpProtocolHandler.java
src/main/java/org/jenkinsci/remoting/engine/JnlpProtocolHandlerFactory.java
src/main/java/org/jenkinsci/remoting/engine/LegacyJnlpConnectionState.java
src/main/java/org/jenkinsci/remoting/engine/LegacyJnlpProtocolHandler.java
src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java

Just to make the protocol deprecation fact more explicit. No functional changes
@reviewbybees

[JENKINS-45841] - Update Remoting Javadoc to indicate the protocol support status

---

pom.xml

Discussion is here: https://groups.google.com/forum/#!searchin/jenkinsci-dev/remoting%7Csort:date/jenkinsci-dev/CDZaG3dr-kc/YqG4blalAQAJ
https://issues.jenkins-ci.org/browse/JENKINS-43985
@reviewbybees

[JENKINS-43985] - Upgrade Remoting Java requirement to Java 8

---

src/main/java/hudson/remoting/ClassFilter.java
src/test/java/hudson/remoting/DefaultClassFilterTest.java

It is a modified version of #178 from @jglick with better error propagation
https://issues.jenkins-ci.org/browse/JENKINS-45522
@reviewbybees

[JENKINS-45522] - Introduce ClassFilter.appendDefaultFilter

---

src/main/java/hudson/remoting/ClassFilter.java

[JENKINS-45522](https://issues.jenkins-ci.org/browse/JENKINS-45522)
Allows us to get rid of some awful reflection in core.
@reviewbybees

[JENKINS-45522] Introduced ClassFilter.appendDefaultFilter

---

pom.xml

Downstream PR for https://github.com/jenkinsci/pom/pull/14
@reviewbybees

Update POM to Jenkins Parent POM 1.38

---

pom.xml

Downstream to https://github.com/jenkinsci/pom/pull/16
@reviewbybees

Bump to latest jenkinsci/pom

---

src/main/java/hudson/remoting/Capability.java
src/main/java/hudson/remoting/Channel.java
src/main/java/hudson/remoting/ChannelBuilder.java
src/main/java/hudson/remoting/ChannelClosedException.java
src/main/java/hudson/remoting/ClassFilter.java
src/main/java/hudson/remoting/Engine.java
src/main/java/hudson/remoting/EngineListener.java
src/main/java/hudson/remoting/ExportTable.java
src/main/java/hudson/remoting/InterceptingExecutorService.java
src/main/java/hudson/remoting/Launcher.java
src/main/java/hudson/remoting/PipeWindow.java
src/main/java/hudson/remoting/Request.java
src/main/java/hudson/remoting/jnlp/Main.java
src/main/java/hudson/remoting/package-info.java
src/main/java/org/jenkinsci/remoting/RoleChecker.java
src/main/java/org/jenkinsci/remoting/RoleSensitive.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
src/main/java/org/jenkinsci/remoting/nio/FifoBuffer.java

I have recently added Javadoc publishing for Remoting, so some polishing would not hurt.
@reviewbybees

Javadoc cleanup

---

pom.xml

POM: Do not Downgrade plugins from parent pom 1.39

---

src/main/java/hudson/remoting/DaemonThreadFactory.java
src/main/java/hudson/remoting/Engine.java
src/main/java/hudson/remoting/FlightRecorderInputStream.java
src/main/java/hudson/remoting/PingThread.java
src/main/java/hudson/remoting/RemoteInputStream.java
src/main/java/hudson/remoting/SynchronousCommandTransport.java
src/main/java/hudson/remoting/forward/CopyThread.java
src/main/java/hudson/remoting/forward/ForwarderFactory.java
src/main/java/hudson/remoting/forward/PortForwarder.java

@reviewbybees
https://issues.jenkins-ci.org/browse/JENKINS-38711

[JENKINS-38711] Add UncaughtExceptionHandlers to the various remoting threads

---

src/main/java/hudson/remoting/RemoteInvocationHandler.java

It just causes the FindBugs warning in the current settings. I doubt it's really required, but I decided to just add it. Let me know if it's better to suppress it.
#206 has not been released yet, so it's safe to just integrate it
@reviewbybees

[JENKINS-47714] - FindBugs: UserRPCRequest should have serialVersionID

---

src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java

I doubt it improves performance much, but makes sense to fix it anyway.

[JENKINS-37566] - FindBugs: Stop using inefficient iterator logic.

---

src/main/java/hudson/remoting/ClassFilter.java

Not a big deal from performance PoV, but cleans the FindBugs warning
@reviewbybees @rysteboe @jglick

[JENKINS-37566] - Get rid of the dead store in RegExpClassFilter#add()

---

src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java

Tests with file access modifications will be skipped, but all other tests are passing now.
https://issues.jenkins-ci.org/browse/JENKINS-38696
@reviewbybees @jtnord

[JENKINS-38696] - Fix Work Directory Manager tests on Windows.

---

src/main/java/hudson/remoting/Channel.java
src/main/java/org/jenkinsci/remoting/engine/EngineUtil.java
src/main/java/org/jenkinsci/remoting/engine/Jnlp3Util.java

Javadoc: cleanup empty tag warnings

---

src/main/java/hudson/remoting/Which.java

I was investigating the reflection usage in the class as a part of Java 9 compat stories. I see no way in cleaning up current reflection usages without testing, so I decided to keep the code as is.
But I did some minor refactoring + added TODO comments.

Minor refactoring of the hudson.remoting.Which class.

---

src/main/java/org/jenkinsci/remoting/protocol/ApplicationLayer.java
src/main/java/org/jenkinsci/remoting/protocol/FilterLayer.java
src/main/java/org/jenkinsci/remoting/protocol/IOHubReadyListener.java
src/main/java/org/jenkinsci/remoting/protocol/IOHubRegistrationCallback.java
src/main/java/org/jenkinsci/remoting/protocol/IOHubRegistrationFutureAdapterImpl.java
src/main/java/org/jenkinsci/remoting/protocol/NetworkLayer.java
src/main/java/org/jenkinsci/remoting/protocol/ProtocolLayer.java
src/main/java/org/jenkinsci/remoting/protocol/ProtocolStack.java
src/main/java/org/jenkinsci/remoting/protocol/cert/BlindTrustX509ExtendedTrustManager.java
src/main/java/org/jenkinsci/remoting/protocol/cert/DelegatingX509ExtendedTrustManager.java
src/main/java/org/jenkinsci/remoting/protocol/cert/PublicKeyMatchingX509ExtendedTrustManager.java
src/main/java/org/jenkinsci/remoting/protocol/cert/ValidityCheckingX509ExtendedTrustManager.java
src/main/java/org/jenkinsci/remoting/protocol/impl/AckFilterLayer.java
src/main/java/org/jenkinsci/remoting/protocol/impl/AgentProtocolClientFilterLayer.java
src/main/java/org/jenkinsci/remoting/protocol/impl/BIONetworkLayer.java
src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeaders.java
src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayer.java
src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionRefusalException.java
src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java
src/main/java/org/jenkinsci/remoting/protocol/impl/PermanentConnectionRefusalException.java
src/main/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.java
src/test/java/org/jenkinsci/remoting/protocol/IOBufferMatcher.java
src/test/java/org/jenkinsci/remoting/protocol/IOBufferMatcherLayer.java

Just some minor polishing while I was around
@reviewbybees @rysteboe @stephenc

Javadoc: Update documentation for JNLP4 components and layers.

---

src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java

Both are not really important, it should just make the FindBugs report clean once other pending changes are integrated.

[JENKINS-37566] - Cleanup FindBugs issues in WorkDirManager.

---

CHANGELOG.md

Changelog: Noting 3.15

---

src/main/java/hudson/remoting/Engine.java
src/main/java/hudson/remoting/InitializeJarCacheMain.java
src/main/java/hudson/remoting/Launcher.java
src/main/java/hudson/remoting/jnlp/Main.java
src/main/java/hudson/remoting/jnlp/MainDialog.java
src/main/java/hudson/remoting/package-info.java

https://issues.jenkins-ci.org/browse/JENKINS-48686

[JENKINS-48686] Switch to calling the agent 'agent'

---

CHANGELOG.md
src/main/java/hudson/remoting/ClassFilter.java

It is a part of the JEP-200 delivery
@reviewbybees

Changelog and Javadoc update towards 2.16

---

Jenkinsfile
settings-azure.xml

Port of https://github.com/jenkinsci/jenkins/pull/2890. Attempting to fix build errors such as those in #204.
@reviewbybees

[INFRA-1176] Use the Azure mirror when building, so we do not try to contact Central

---

src/main/java/hudson/remoting/AbstractByteArrayCommandTransport.java
src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
src/main/java/hudson/remoting/AbstractSynchronousByteArrayCommandTransport.java
src/main/java/hudson/remoting/Channel.java
src/main/java/hudson/remoting/ClassicCommandTransport.java
src/main/java/hudson/remoting/Command.java
src/main/java/hudson/remoting/GCCommand.java
src/main/java/hudson/remoting/Pipe.java
src/main/java/hudson/remoting/ProxyInputStream.java
src/main/java/hudson/remoting/RemoteClassLoader.java
src/main/java/hudson/remoting/RemoteInvocationHandler.java
src/main/java/hudson/remoting/Request.java
src/main/java/hudson/remoting/Response.java
src/main/java/hudson/remoting/UnexportCommand.java
src/main/java/org/jenkinsci/remoting/util/LoggingChannelListener.java
src/test/java/hudson/remoting/ClassFilterTest.java

Basis for [JENKINS-27035](https://issues.jenkins-ci.org/browse/JENKINS-27035). See downstream https://github.com/jenkinsci/jenkins/pull/3071 for context and progress.

[JENKINS-27035] Introduced Channel.Listener.read/write

---

docs/logging.md
src/main/java/hudson/remoting/Channel.java
src/main/java/hudson/remoting/Command.java
src/main/java/hudson/remoting/Request.java
src/main/java/hudson/remoting/Response.java
src/main/java/org/jenkinsci/remoting/util/LoggingChannelListener.java

[JENKINS-27035] More documentation

---

CHANGELOG.md

@reviewbybees @rysteboe @jglick

Changelog: Noting 3.17

---

src/main/java/hudson/remoting/Engine.java

@reviewbybees
https://issues.jenkins-ci.org/browse/JENKINS-49415

[JENKINS-49415] Add additional UncaughtExceptionHandler

---

CHANGELOG.md

Changelog: Noting JENKINS-45897 in the 3.17 release + 3.18 heads-up

---

src/main/java/hudson/remoting/AbstractByteArrayCommandTransport.java
src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java

@reviewbybees
https://issues.jenkins-ci.org/browse/JENKINS-49472

[JENKINS-49472] Log channel name if command not constructed

---

pom.xml
src/main/java/hudson/remoting/AbstractByteArrayCommandTransport.java
src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
src/main/java/hudson/remoting/Channel.java

https://issues.jenkins-ci.org/browse/JENKINS-49472
https://issues.jenkins-ci.org/browse/JENKINS-49480
@reviewbybees

Add additional logging

---

pom.xml

Downstream of https://github.com/jenkinsci/pom/pull/18
@reviewbybees @dwnusbaum @rysteboe

Update Remoting to Parent POM 1.40 with integrated FindBugs check

---

CHANGELOG.md

Changelog: Noting 3.18

---

CHANGELOG.md

Note PR 258 in 3.18 changelog

---

CHANGELOG.md

Add jenkins core release version for 3.18

---

src/test/java/org/jenkinsci/remoting/engine/JnlpProtocolHandlerTest.java

Some of this is similar to the simplifications for NetworkLayerTest in e9c1af14 (See #270). This test has also been hitting sporadic hangs / failures, primarily on certain OSes, etc. These mostly occur in preClose0() also. Similar to that test, part of the solution here is to eliminate the repetition of the exact same test.
As part of understanding and cleaning up this test, I also made a major effort to remove other duplication. And to improve naming and clarity. The individual test methods were lengthy, with lots of duplicated code, making it hard to understand what they were doing. Indeed some of the tests didn't actually match their name / intention. I extracted out the commonality and tried to make it clearer the variation in each test.
This test had continued testing all old …

[JENKINS-51379] Simplify JnlpProtocolHandlerTest.

---

pom.xml

https://github.com/jenkinsci/pom/pull/34

Picking up SUREFIRE-1588 workaround

---

CHANGELOG.md

Prepare changelog update for 3.28.

Update changelog for 3.28.

---

src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java

A log record was created but never logged.
/cc @oleg-nenashev

[JENKINS-55976] - Add missing log call

---

src/main/java/hudson/remoting/URLDeserializationHelper.java
src/test/java/hudson/remoting/URLDeserializatinHelperTest.java

SafeURLStreamHandler needs to be able to handle connections via a proxy
add test for opening with proxy

[JENKINS-57107] SafeURLStreamHandler with proxy

---

.github/release-drafter.yml

Enable Release Drafter for Remoting module.

Enable Release Drafter.

---

docs/tcpAgent.md
src/main/java/hudson/remoting/Callable.java
src/main/java/hudson/remoting/Channel.java
src/main/java/hudson/remoting/ChannelClosedException.java
src/main/java/hudson/remoting/Command.java
src/main/java/hudson/remoting/Engine.java
src/main/java/hudson/remoting/ExportTable.java
src/main/java/hudson/remoting/ProxyWriter.java
src/main/java/hudson/remoting/URLDeserializationHelper.java
src/main/java/hudson/remoting/jnlp/Main.java
src/main/java/org/jenkinsci/remoting/CallableDecorator.java
src/main/java/org/jenkinsci/remoting/ChannelStateException.java
src/main/java/org/jenkinsci/remoting/Role.java
src/main/java/org/jenkinsci/remoting/engine/EngineUtil.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
src/main/java/org/jenkinsci/remoting/util/PathUtils.java
src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java

I had a few that I needed to update for the 3.34 release.
In trying to do those, I noticed there are a bunch of old ones. There is very little value in the ones that are 2, 3, or certainly 5 years old. If I could quickly identify the correct value, I added it, otherwise I removed the tag.

Update "@since TODO" tags.

---

src/main/java/hudson/remoting/DumbClassLoaderBridge.java
src/main/java/hudson/remoting/jnlp/MainDialog.java
src/main/java/hudson/remoting/jnlp/MainMenu.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointConfigurator.java

Cleanup unused, star imports and deprecated code

---

.github/release-drafter.yml

Extend the same as all the others.

Fix release drafter extends.

---

src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
src/main/java/hudson/remoting/Channel.java
src/main/java/hudson/remoting/NamingThreadFactory.java
src/main/java/hudson/remoting/RemoteClassLoader.java
src/main/java/hudson/remoting/RemoteInvocationHandler.java
src/main/java/org/jenkinsci/remoting/protocol/ProtocolLayer.java
src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java
src/main/java/org/jenkinsci/remoting/util/ByteBufferQueueInputStream.java
src/main/java/org/jenkinsci/remoting/util/ByteBufferQueueOutputStream.java
src/main/java/org/jenkinsci/remoting/util/ByteBufferUtils.java
src/main/java/org/jenkinsci/remoting/util/FastByteBufferQueueInputStream.java
src/main/java/org/jenkinsci/remoting/util/IOUtils.java
src/main/java/org/jenkinsci/remoting/util/SettableFuture.java
src/main/java/org/jenkinsci/remoting/util/ThrowableUtils.java

Cleanup the remaining since documentation

Fix missing `@since` annotations in Javadoc

---

src/test/java/hudson/remoting/ChannelFilterTest.java
src/test/java/hudson/remoting/DiagnosedStreamCorruptionExceptionTest.java
src/test/java/hudson/remoting/ForkRunner.java
src/test/java/hudson/remoting/throughput/Receiver.java
src/test/java/hudson/remoting/throughput/Sender.java
src/test/java/org/jenkinsci/remoting/engine/ChannelCiphersTest.java
src/test/java/org/jenkinsci/remoting/engine/EngineUtilTest.java
src/test/java/org/jenkinsci/remoting/engine/HandshakeCiphersTest.java
src/test/java/org/jenkinsci/remoting/engine/Jnlp3UtilTest.java

- Cleanup more deprecated code
- Suppress warnings for tests against deprecated code

Cleanup deprecated code

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java

Publish Incrementals

---

pom.xml

Just for testing the current release candidate

Upgrade the parent POM from 1.52 to 1.53

---

Jenkinsfile
settings-azure.xml

[INFRA-2435](https://issues.jenkins-ci.org/browse/INFRA-2435)

[INFRA-2435] repo.azure.jenkins.io is dead

---

src/main/java/hudson/remoting/RemoteClassLoader.java

This PR is a straight-forward auto-format of RemoteClassLoader using IntelliJ. This is part of the modernization and clean-up effort I'm pursuing. For easing reviews, I decided to make this its own PR.

Auto-format RemoteClassLoader.

---

README.md

Follow-up to https://issues.jenkins-ci.org/browse/JENKINS-62316 where the Jenkins user is asking for download links

Add a Downloads section to README

---

.github/FUNDING.yml

https://github.com/jenkinsci/jep/tree/master/jep/15

[JEP-15] - Add sponsorhip metadata to the repository

---

Jenkinsfile

Use Warning-NG instead of findbugs.

---

pom.xml

Specify the jarsigner plugin version to quiet a Maven warning.

Specify jarsigner version.

---

src/main/java/org/jenkinsci/remoting/protocol/cert/BlindTrustX509ExtendedTrustManager.java
src/main/java/org/jenkinsci/remoting/protocol/cert/PublicKeyMatchingX509ExtendedTrustManager.java
src/main/java/org/jenkinsci/remoting/protocol/cert/ValidityCheckingX509ExtendedTrustManager.java

A bit of cleanup started in #442 but not completed.

No more `@IgnoreJRERequirement`s

---

src/test/java/hudson/remoting/PrefetchingTest.java

The fewer references to `AntClassLoader` we have in the ecosystem, the better.

Replace `AntClassLoader` with `URLClassLoader` in tests

---

pom.xml
src/main/java/hudson/remoting/ClassFilter.java
src/spotbugs/excludeFilter.xml

Like #493, but suppresses SpotBugs warnings.

Bump parent POM from 1.67 to 1.69

---

src/main/java/hudson/remoting/Channel.java
src/main/java/hudson/remoting/Launcher.java
src/main/java/hudson/remoting/PingThread.java
src/main/java/hudson/remoting/RemoteInvocationHandler.java
src/test/java/JarCertDump.java
src/test/java/hudson/remoting/ChecksumTest.java
src/test/java/hudson/remoting/DefaultClassFilterTest.java
src/test/java/hudson/remoting/DiagnosedStreamCorruptionExceptionTest.java
src/test/java/hudson/remoting/DummyClassLoader.java
src/test/java/hudson/remoting/FileSystemJarCacheTest.java
src/test/java/hudson/remoting/PipeTest.java
src/test/java/hudson/remoting/RmiTestBase.java
src/test/java/hudson/remoting/throughput/DumbReceiver.java
src/test/java/hudson/remoting/throughput/Sender.java
src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
src/test/java/org/jenkinsci/remoting/protocol/IOHubTest.java
src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersTest.java

Replaces deprecated APIs. There still some left though.
For those with more experience in this project: Please have a look at the charset related changes.
-----------------------------------------------

Replace deprecated APIs

---

src/main/java/hudson/remoting/InitializeJarCacheMain.java

Replaced own implementation with java 7 api

Replaced own implementation with java 7 api

---

src/main/java/hudson/remoting/Channel.java
src/main/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.java
src/main/java/org/jenkinsci/remoting/util/VersionNumber.java
src/test/java/hudson/remoting/RegExpBenchmark.java
src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackLoopbackLoadStress.java

Minor improvements:
* use `Comparator.reverseOrder()` instead of own implementation
* `printf` instead of `println` + `String.format`
* use `equalsIgnoreCase` instead of `toLowerCase` which might be faster.

Minor internal improvements

---

.github/workflows/release-drafter.yml

I have uninstalled the app from this repo

Switch release drafter to GitHub action

---

pom.xml

ref https://github.com/jenkinsci/remoting/pull/532#issuecomment-1125014644

Push changes as part of release

---

src/main/java/hudson/remoting/Engine.java

[JENKINS-68542](https://issues.jenkins.io/browse/JENKINS-68542)
This follows a similar logic to what is done for the [TCP path](https://github.com/jenkinsci/remoting/blob/6f32e99562f734e66f024aa44b777a3fdd6e9292/src/main/java/hudson/remoting/Engine.java#L1103-L1109).
* Build the header map before entering the infinite loop.
* Capture the cookie as processing the initial response and put it in the header map
* Further reconnection attempts use the updated header map.
Tested manually by launching a controller, then attaching an agent using websockets.
* Then start a second instance of the same agent => it gets rejected.
* Then start again the second instance by injecting the cookie through a system property => the second instance connects, the first instance gets disconnected. It tries to …

[JENKINS-68542] [WebSocket] Capture cookie returned by server and reuse for reconnection attempts

---

Jenkinsfile

By cherry-picking #517 (at least the Jenkinsfile part)

Attempt to fix CI

---

CONTRIBUTING.md

Remove outdated freenode documentation

---

src/main/java/hudson/remoting/Capability.java
src/main/java/hudson/remoting/DumbClassLoaderBridge.java
src/main/java/hudson/remoting/Engine.java
src/main/java/hudson/remoting/Which.java
src/main/java/org/jenkinsci/remoting/Role.java
src/main/java/org/jenkinsci/remoting/RoleChecker.java
src/main/java/org/jenkinsci/remoting/engine/JnlpConnectionState.java
src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
src/test/java/OISInterception.java
src/test/java/hudson/remoting/DefaultClassFilterTest.java
src/test/java/hudson/remoting/DummyClassLoader.java
src/test/java/hudson/remoting/EngineTest.java
src/test/java/hudson/remoting/PrefetchingTest.java
src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackImplTest.java
src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackLoopbackLoadStress.java
src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayerTest.java
src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersTest.java
src/test/java/org/jenkinsci/remoting/util/ByteBufferQueueInputStreamTest.java
src/test/java/org/jenkinsci/remoting/util/FastByteBufferQueueInputStreamTest.java

Testing done: [Core test suite passed](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6700/13/), [BOM test suite passed](https://ci.jenkins.io/job/Tools/job/bom/job/PR-1234/5/)

Use Java 11 language features where possible

---

src/main/java/org/jenkinsci/remoting/util/AnonymousClassWarnings.java

Amending #259, reverting #523, superseding #558,  and probably fixing [JENKINS-68954](https://issues.jenkins.io/browse/JENKINS-68954) and fixing [JENKINS-65873](https://issues.jenkins.io/browse/JENKINS-65873) more thoroughly and simply.

[JENKINS-65873] [JENKINS-68954] Optimize `AnonymousClassWarnings`

---

src/main/java/org/jenkinsci/remoting/util/AnonymousClassWarnings.java

(cherry picked from commit b940aae4f72e9cc72fee5435ffcdd6f0706fe3a9)
Integrating as per request into the stable branch of remoting for 2.346.3

[JENKINS-65873] [JENKINS-68954] Optimize `AnonymousClassWarnings` (#559)

---

src/main/java/hudson/remoting/RemoteClassLoader.java

Observed a stack trace from a controller at the moment an inbound (TCP) agent was disconnecting at the completion of a build:
```
SEVERE	o.j.r.p.impl.NIONetworkLayer#ready: [JNLP4-connect connection from …] Uncaught IllegalStateException
java.util.concurrent.ExecutionException: Invalid object ID 2 iota=18
at hudson.remoting.ExportTable.diagnoseInvalidObjectId(ExportTable.java:441)
at hudson.remoting.ExportTable.get(ExportTable.java:358)
at hudson.remoting.Channel.getExportedObject(Channel.java:824)
at hudson.remoting.RemoteClassLoader$RemoteIClassLoader.readResolve(RemoteClassLoader.java:1279)
Caused: java.lang.IllegalStateException: Cannot resolve remoting classloader
at hudson.remoting.RemoteClassLoader$RemoteIClassLoader.readResolve(RemoteClassLoader.java:1282)
at …
```

Better robustness for `RemoteIClassLoader.readResolve`

---

src/main/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/InetAddressValidator.java
src/main/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/RegexValidator.java
src/test/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/InetAddressValidatorTest.java
src/test/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/RegexValidatorTest.java

Side-port of jenkinsci/jenkins#6048 to the corresponding copypasta in Remoting.
Ran the unit tests locally.

Upgrade Apache Commons Validator from 1.6 to 1.7

---

src/main/java/hudson/remoting/Launcher.java

Also use a buffer rather than reading one byte at a time (!).

Use Java 11 method where possible

---

src/main/java/hudson/remoting/SocketChannelStream.java

See 798153ab8387c3a83b3b1e5b09f353b71b843356.

Updating comment in `SocketChannelStream` about JDK-8222774

---

src/main/java/hudson/remoting/JarCacheSupport.java

For a while now, users have been complaining about jobs failing with an (agent-side) stack trace like e.g.
```
java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method)
at java.lang.Thread.start(Thread.java:717)
at hudson.remoting.AtmostOneThreadExecutor.execute(AtmostOneThreadExecutor.java:104)
at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
at org.jenkinsci.remoting.util.ExecutorServiceUtils.submitAsync(ExecutorServiceUtils.java:58)
at hudson.remoting.JarCacheSupport.resolve(JarCacheSupport.java:77)
at hudson.remoting.ResourceImageInJar._resolveJarURL(ResourceImageInJar.java:93)
at hudson.remoting.ResourceImageInJar.resolve(ResourceImageInJar.java:45)
at …
```

Avoid continual thread replacement in `JarCacheSupport`

---

docs/class-loading.md

The document I wish I had before I started reading this code.

Add documentation about remote class loading subsystem

---

src/test/java/hudson/remoting/EngineTest.java

Small improvements I noticed when tweaking other code, leading to some tests hanging

Improvements to EngineTest

---

src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java

Signed-off-by: Olivier Lamy <olamy@apache.org>

Avoid possible NPE when using websocket

---

Jenkinsfile

Revert #783, which was merely a workaround for https://github.com/jenkins-infra/helpdesk/issues/4569 (which is now fixed).
CI build

Decrease ci.jenkins.io timeout from 25 to 20

---

src/main/java/hudson/remoting/AbstractByteArrayCommandTransport.java
src/main/java/hudson/remoting/Capability.java
src/main/java/hudson/remoting/ChannelBuilder.java
src/main/java/hudson/remoting/LocalChannel.java
src/main/java/hudson/remoting/RemoteInputStream.java
src/spotbugs/excludesFilter.xml

This SpotBugs violation was trivially fixed with IntelliJ's automated refactoring tools and seems safe. Review with "Hide Whitespace" for an easier time understanding the diff.
`mvn clean verify -DskipTests`

Fix `SIC_INNER_SHOULD_BE_STATIC_ANON` violations

---

src/main/java/hudson/remoting/Checksum.java
src/main/java/hudson/remoting/Engine.java
src/main/java/hudson/remoting/Which.java
src/main/java/org/jenkinsci/remoting/engine/HostPort.java
src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
src/test/java/hudson/remoting/ChannelTest.java
src/test/java/hudson/remoting/ClassRemotingTest.java
src/test/java/hudson/remoting/PipeTest.java
src/test/java/org/jenkinsci/remoting/engine/PropertiesStringMatcher.java
src/test/java/org/jenkinsci/remoting/org/apache/commons/net/util/SubnetUtilsTest.java
src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayerTest.java

Fix a few trivial IntelliJ warnings.
`mvn clean verify`

Miscellaneous code cleanup

---

src/main/java/org/jenkinsci/remoting/util/DurationStyle.java

I plan to expose it through jenkins core `SystemProperties`

Unrestrict DurationStyle
